export type HeaderAliasMap = Record<string, string[]>;
export type HeaderAliasSections = Record<string, HeaderAliasMap>;

export const HEADER_ALIAS_SECTIONS: HeaderAliasSections = {
  patient: {
    patient_id: ['patient_identifier', 'patient_mrn', 'mrn', 'medical_record_number', 'patientid'],
    patient_first_name: ['first_name', 'fname', 'given_name', 'given', 'patient_given', 'patient_given_name'],
    patient_middle_name: ['middle_name', 'middlename'],
    patient_last_name: ['last_name', 'lname', 'family_name', 'surname', 'patient_family', 'patient_family_name'],
    patient_name: ['name', 'patientname', 'full_name', 'patient_full_name', 'pt_name'],
    patient_gender: ['gender', 'sex', 'gndr'],
    patient_birth_date: ['dob', 'date_of_birth', 'birth_date', 'birthdate'],
    patient_phone: ['phone', 'phone_number', 'mobile', 'cell', 'cell_phone', 'patient_phone_number', 'patient_mobile', 'patient_home_phone'],
    patient_email: ['email', 'email_address'],
    patient_address_line1: ['address', 'address1', 'address_line1', 'street', 'street_address', 'patient_address1', 'patient_address_1'],
    patient_address_line2: ['address2', 'address_line2', 'street2', 'street_address_2', 'patient_address2', 'patient_address_2'],
    patient_city: ['city', 'town'],
    patient_state: ['state', 'province', 'region', 'patient_province'],
    patient_postal_code: ['zip', 'zipcode', 'postal', 'postal_code', 'patient_zip'],
    patient_country: ['country']
  },
  encounter: {
    encounter_id: ['visit_id', 'encounter_identifier', 'encounterid', 'visitid'],
    encounter_class: ['encounter_type', 'visit_class', 'encounterclass'],
    encounter_start: ['encounter_start_time', 'visit_start', 'visit_start_time', 'admit_time', 'admit_datetime'],
    encounter_location: ['visit_location', 'encounter_room'],
    encounter_status: ['encounterstate'],
    encounter_practitioner_id: ['encounter_participant_id', 'encounter_practitioner_ids'],
    encounter_service_provider_id: ['service_provider_id', 'service_provider_organization_id']
  },
  observation: {
    observation_id: ['obs_id', 'observation_identifier', 'observationid'],
    observation_code: ['obs_code', 'test_code', 'loinc_code', 'observationcode'],
    observation_code_system: ['obs_code_system', 'loinc_system'],
    observation_display: ['obs_display', 'test_name', 'observation_name', 'observation_display_name'],
    observation_value: ['obs_value', 'result_value'],
    observation_unit: ['obs_unit', 'result_unit'],
    observation_date: ['obs_date', 'observation_datetime', 'observation_time', 'recorded_datetime'],
    observation_status: ['obs_status', 'result_status']
  },
  medication: {
    medication_id: ['med_id', 'medication_identifier', 'medicationid'],
    medication_code: ['med_code', 'rxnorm_code', 'ndc_code', 'medicationcode'],
    medication_code_system: ['med_code_system', 'rxnorm_system', 'ndc_system'],
    medication_display: ['med_display', 'medication_name', 'drug_name']
  },
  medicationRequest: {
    medication_request_id: ['med_request_id', 'prescription_id', 'order_id'],
    medication_status: ['med_status', 'medication_request_status'],
    medication_authored_on: ['med_authored_on', 'order_date'],
    medication_dose: ['med_dose'],
    medication_dose_unit: ['med_dose_unit', 'dose_unit'],
    medication_route: ['med_route'],
    medication_route_display: ['med_route_display', 'route_display'],
    medication_sig: ['med_sig', 'sig', 'instructions']
  },
  medicationStatement: {
    medication_statement_id: ['med_statement_id', 'medicationstatement_id'],
    medication_statement_status: ['med_statement_status', 'medication_statement_state'],
    medication_statement_category: ['med_statement_category', 'medication_statement_type'],
    medication_statement_medication_code: ['med_statement_code', 'medication_code'],
    medication_statement_medication_code_system: ['med_statement_code_system', 'medication_code_system'],
    medication_statement_medication_display: ['med_statement_display', 'medication_display'],
    medication_statement_subject_id: ['med_statement_subject_id', 'subject_id', 'patient_id'],
    medication_statement_encounter_id: ['med_statement_encounter_id', 'encounter_id'],
    medication_statement_effective_date: ['med_statement_effective_date', 'effective_date'],
    medication_statement_effective_start: ['med_statement_effective_start', 'effective_start'],
    medication_statement_effective_end: ['med_statement_effective_end', 'effective_end'],
    medication_statement_date_asserted: ['med_statement_date_asserted', 'date_asserted'],
    medication_statement_author: ['med_statement_author', 'author_id'],
    medication_statement_information_source: ['med_statement_information_source', 'information_source'],
    medication_statement_reason: ['med_statement_reason', 'reason'],
    medication_statement_note: ['med_statement_note', 'note'],
    medication_statement_dose: ['med_statement_dose', 'dose'],
    medication_statement_dose_unit: ['med_statement_dose_unit', 'dose_unit'],
    medication_statement_route: ['med_statement_route', 'route'],
    medication_statement_route_display: ['med_statement_route_display', 'route_display']
  },
  procedure: {
    procedure_id: ['proc_id', 'procedure_identifier', 'procedureid'],
    procedure_status: ['proc_status', 'procedure_status'],
    procedure_category: ['proc_category', 'procedure_category'],
    procedure_code: ['proc_code', 'procedure_code'],
    procedure_code_system: ['proc_code_system', 'procedure_code_system'],
    procedure_display: ['proc_display', 'procedure_display', 'procedure_name'],
    procedure_subject_id: ['proc_subject_id', 'subject_id', 'patient_id'],
    procedure_encounter_id: ['proc_encounter_id', 'encounter_id'],
    procedure_occurrence_date: ['proc_occurrence_date', 'occurrence_date'],
    procedure_occurrence_start: ['proc_occurrence_start', 'occurrence_start'],
    procedure_occurrence_end: ['proc_occurrence_end', 'occurrence_end'],
    procedure_recorded: ['proc_recorded', 'recorded'],
    procedure_performer_id: ['proc_performer_id', 'performer_id'],
    procedure_location: ['proc_location', 'location'],
    procedure_reason: ['proc_reason', 'reason'],
    procedure_body_site: ['proc_body_site', 'body_site'],
    procedure_note: ['proc_note', 'note']
  },
  condition: {
    condition_id: ['cond_id', 'condition_identifier', 'conditionid'],
    condition_clinical_status: ['cond_clinical_status', 'clinical_status'],
    condition_verification_status: ['cond_verification_status', 'verification_status'],
    condition_category: ['cond_category', 'condition_category'],
    condition_severity: ['cond_severity', 'severity'],
    condition_code: ['cond_code', 'condition_code'],
    condition_code_system: ['cond_code_system', 'condition_code_system'],
    condition_display: ['cond_display', 'condition_display', 'condition_name'],
    condition_body_site: ['cond_body_site', 'body_site'],
    condition_subject_id: ['cond_subject_id', 'subject_id', 'patient_id'],
    condition_encounter_id: ['cond_encounter_id', 'encounter_id'],
    condition_onset_date: ['cond_onset_date', 'onset_date'],
    condition_onset_start: ['cond_onset_start', 'onset_start'],
    condition_onset_end: ['cond_onset_end', 'onset_end'],
    condition_onset_text: ['cond_onset_text', 'onset_text'],
    condition_abatement_date: ['cond_abatement_date', 'abatement_date'],
    condition_abatement_start: ['cond_abatement_start', 'abatement_start'],
    condition_abatement_end: ['cond_abatement_end', 'abatement_end'],
    condition_abatement_text: ['cond_abatement_text', 'abatement_text'],
    condition_recorded_date: ['cond_recorded_date', 'recorded_date'],
    condition_note: ['cond_note', 'note']
  },
  appointment: {
    appointment_id: ['appt_id', 'appointment_identifier', 'appointmentid'],
    appointment_status: ['appt_status', 'status'],
    appointment_description: ['appt_description', 'description'],
    appointment_start: ['appt_start', 'start'],
    appointment_end: ['appt_end', 'end'],
    appointment_minutes_duration: ['appt_minutes_duration', 'minutes_duration', 'duration_minutes'],
    appointment_created: ['appt_created', 'created'],
    appointment_cancellation_date: ['appt_cancellation_date', 'cancellation_date'],
    appointment_subject_id: ['appt_subject_id', 'subject_id', 'patient_id'],
    appointment_participant_id: ['appt_participant_id', 'participant_id'],
    appointment_participant_status: ['appt_participant_status', 'participant_status'],
    appointment_note: ['appt_note', 'note']
  },
  schedule: {
    schedule_id: ['sched_id', 'schedule_identifier', 'scheduleid'],
    schedule_active: ['sched_active', 'active'],
    schedule_name: ['sched_name', 'name'],
    schedule_actor_id: ['sched_actor_id', 'actor_id'],
    schedule_start: ['sched_start', 'start'],
    schedule_end: ['sched_end', 'end'],
    schedule_comment: ['sched_comment', 'comment'],
    schedule_service_category: ['sched_service_category', 'service_category'],
    schedule_service_type: ['sched_service_type', 'service_type'],
    schedule_specialty: ['sched_specialty', 'specialty']
  },
  slot: {
    slot_id: ['slot_id', 'slot_identifier'],
    slot_status: ['slot_status', 'status'],
    slot_start: ['slot_start', 'start'],
    slot_end: ['slot_end', 'end'],
    slot_schedule_id: ['slot_schedule_id', 'schedule_id'],
    slot_overbooked: ['slot_overbooked', 'overbooked'],
    slot_comment: ['slot_comment', 'comment'],
    slot_service_category: ['slot_service_category', 'service_category'],
    slot_service_type: ['slot_service_type', 'service_type'],
    slot_specialty: ['slot_specialty', 'specialty'],
    slot_appointment_type: ['slot_appointment_type', 'appointment_type']
  },
  diagnosticReport: {
    diagnostic_report_id: ['diag_report_id', 'diagnosticreport_id'],
    diagnostic_report_status: ['diag_report_status', 'diagnostic_report_status'],
    diagnostic_report_code: ['diag_report_code', 'diagnostic_report_code'],
    diagnostic_report_code_system: ['diag_report_code_system', 'diagnostic_report_code_system'],
    diagnostic_report_display: ['diag_report_display', 'diagnostic_report_display'],
    diagnostic_report_category: ['diag_report_category', 'diagnostic_report_category'],
    diagnostic_report_subject_id: ['diag_report_subject_id', 'subject_id', 'patient_id'],
    diagnostic_report_encounter_id: ['diag_report_encounter_id', 'encounter_id'],
    diagnostic_report_effective_date: ['diag_report_effective_date', 'effective_date'],
    diagnostic_report_effective_start: ['diag_report_effective_start', 'effective_start'],
    diagnostic_report_effective_end: ['diag_report_effective_end', 'effective_end'],
    diagnostic_report_issued: ['diag_report_issued', 'issued'],
    diagnostic_report_performer_id: ['diag_report_performer_id', 'performer_id'],
    diagnostic_report_result_ids: ['diag_report_result_ids', 'result_ids'],
    diagnostic_report_conclusion: ['diag_report_conclusion', 'conclusion'],
    diagnostic_report_note: ['diag_report_note', 'note']
  },
  relatedPerson: {
    related_person_id: ['related_person_id', 'relatedperson_id', 'rp_id'],
    related_person_active: ['related_person_active', 'active'],
    related_person_patient_id: ['related_person_patient_id', 'patient_id'],
    related_person_relationship: ['related_person_relationship', 'relationship'],
    related_person_first_name: ['related_person_first_name', 'first_name'],
    related_person_last_name: ['related_person_last_name', 'last_name'],
    related_person_phone: ['related_person_phone', 'phone'],
    related_person_email: ['related_person_email', 'email'],
    related_person_gender: ['related_person_gender', 'gender'],
    related_person_birth_date: ['related_person_birth_date', 'birth_date'],
    related_person_address_line1: ['related_person_address_line1', 'address_line1'],
    related_person_address_line2: ['related_person_address_line2', 'address_line2'],
    related_person_city: ['related_person_city', 'city'],
    related_person_state: ['related_person_state', 'state'],
    related_person_postal_code: ['related_person_postal_code', 'postal_code'],
    related_person_country: ['related_person_country', 'country']
  },
  location: {
    location_id: ['loc_id', 'location_identifier', 'locationid'],
    location_status: ['loc_status', 'status'],
    location_name: ['loc_name', 'name'],
    location_alias: ['loc_alias', 'alias'],
    location_description: ['loc_description', 'description'],
    location_mode: ['loc_mode', 'mode'],
    location_type: ['loc_type', 'type'],
    location_address_line1: ['loc_address_line1', 'address_line1'],
    location_address_line2: ['loc_address_line2', 'address_line2'],
    location_city: ['loc_city', 'city'],
    location_state: ['loc_state', 'state'],
    location_postal_code: ['loc_postal_code', 'postal_code'],
    location_country: ['loc_country', 'country'],
    location_managing_org_id: ['loc_managing_org_id', 'managing_organization_id'],
    location_part_of_id: ['loc_part_of_id', 'part_of_id']
  },
  episodeOfCare: {
    episode_of_care_id: ['episode_id', 'episodeofcare_id', 'eoc_id'],
    episode_status: ['status'],
    episode_type: ['type'],
    episode_patient_id: ['patient_id', 'subject_id'],
    episode_managing_org_id: ['managing_organization_id', 'managing_org_id'],
    episode_period_start: ['period_start', 'start_date', 'start'],
    episode_period_end: ['period_end', 'end_date', 'end'],
    episode_care_manager_id: ['care_manager_id', 'care_manager'],
    episode_care_team_ids: ['care_team_ids', 'care_team_id', 'care_team'],
    episode_account_ids: ['account_ids', 'account_id', 'account'],
    episode_referral_request_ids: ['referral_request_ids', 'referral_request_id', 'referral_request'],
    episode_reason: ['reason'],
    episode_diagnosis: ['diagnosis'],
    episode_status_history_status: ['status_history_status'],
    episode_status_history_start: ['status_history_start'],
    episode_status_history_end: ['status_history_end']
  },
  documentReference: {
    document_id: ['doc_id', 'document_identifier', 'documentid'],
    document_title: ['doc_title'],
    document_description: ['doc_description'],
    document_format: ['doc_format'],
    document_url: ['doc_url'],
    document_data: ['doc_data'],
    document_content_type: ['doc_content_type', 'mime_type'],
    document_status: ['doc_status']
  },
  practitioner: {
    practitioner_id: ['provider_id', 'clinician_id', 'practitioner_identifier', 'practitionerid'],
    practitioner_first_name: ['practitioner_given', 'practitioner_given_name', 'provider_first_name', 'clinician_first_name'],
    practitioner_middle_name: ['practitioner_middlename', 'provider_middle_name', 'clinician_middle_name'],
    practitioner_last_name: ['practitioner_family', 'practitioner_family_name', 'provider_last_name', 'clinician_last_name'],
    practitioner_name: ['practitioner_full_name', 'provider_name', 'clinician_name'],
    practitioner_gender: ['practitioner_sex', 'provider_gender', 'clinician_gender'],
    practitioner_birth_date: ['practitioner_dob', 'provider_dob', 'clinician_dob'],
    practitioner_phone: ['practitioner_phone_number', 'provider_phone', 'clinician_phone', 'practitioner_mobile', 'practitioner_home_phone'],
    practitioner_email: ['practitioner_email_address', 'provider_email', 'clinician_email'],
    practitioner_address_line1: ['practitioner_address', 'practitioner_address1', 'provider_address1', 'practitioner_address_1'],
    practitioner_address_line2: ['practitioner_address2', 'provider_address2', 'practitioner_address_2'],
    practitioner_city: ['practitioner_city', 'provider_city'],
    practitioner_state: ['practitioner_state', 'provider_state', 'practitioner_province'],
    practitioner_postal_code: ['practitioner_zip', 'provider_zip', 'practitioner_postal'],
    practitioner_country: ['practitioner_country', 'provider_country'],
    practitioner_qualification_code: ['practitioner_qualification', 'provider_qualification_code'],
    practitioner_qualification_system: ['practitioner_qualification_system', 'provider_qualification_system'],
    practitioner_qualification_display: ['practitioner_qualification_display', 'provider_qualification_display'],
    practitioner_active: ['provider_active', 'clinician_active']
  },
  practitionerRole: {
    practitioner_role_id: ['role_id', 'practitionerrole_id', 'practitioner_role_identifier'],
    practitioner_role_practitioner_id: ['role_practitioner_id', 'role_provider_id'],
    practitioner_role_organization_id: ['role_organization_id'],
    practitioner_role_code: ['role_code', 'practitionerrole_code'],
    practitioner_role_code_system: ['role_code_system'],
    practitioner_role_code_display: ['role_code_display'],
    practitioner_role_specialty: ['role_specialty', 'specialty_code'],
    practitioner_role_specialty_system: ['specialty_system'],
    practitioner_role_specialty_display: ['specialty_display'],
    practitioner_role_period_start: ['role_period_start', 'role_start'],
    practitioner_role_period_end: ['role_period_end', 'role_end'],
    practitioner_role_active: ['role_active']
  },
  organization: {
    organization_id: ['org_id', 'organization_identifier', 'organizationid'],
    organization_name: ['org_name', 'facility_name'],
    organization_alias: ['org_alias', 'organization_aliases'],
    organization_type_code: ['org_type_code', 'organization_type'],
    organization_type_system: ['org_type_system'],
    organization_type_display: ['org_type_display'],
    organization_phone: ['org_phone', 'organization_phone_number'],
    organization_email: ['org_email', 'organization_email_address'],
    organization_address_line1: ['org_address', 'org_address1', 'organization_address1', 'organization_address_1'],
    organization_address_line2: ['org_address2', 'organization_address2', 'organization_address_2'],
    organization_city: ['org_city', 'organization_city'],
    organization_state: ['org_state', 'organization_state', 'organization_province'],
    organization_postal_code: ['org_zip', 'organization_zip', 'organization_postal'],
    organization_country: ['org_country', 'organization_country'],
    organization_part_of: ['org_parent_id', 'parent_organization_id', 'organization_parent_id'],
    organization_active: ['org_active']
  }
};

export const HEADER_ALIASES: HeaderAliasMap = Object.values(HEADER_ALIAS_SECTIONS)
  .reduce((acc, section) => ({ ...acc, ...section }), {} as HeaderAliasMap);
