export type HeaderAliasMap = Record<string, string[]>;
export type HeaderAliasSections = Record<string, HeaderAliasMap>;

export const HEADER_ALIAS_SECTIONS: HeaderAliasSections = {
  patient: {
    patient_id: ['patient_identifier', 'patient_mrn', 'mrn', 'medical_record_number', 'medical_record_no', 'patientid', 'pat_id', 'person_id', 'pid'],
    patient_first_name: ['first_name', 'fname', 'given_name', 'given', 'patient_given', 'patient_given_name', 'patient_first'],
    patient_middle_name: ['middle_name', 'middlename'],
    patient_last_name: ['last_name', 'lname', 'family_name', 'surname', 'patient_family', 'patient_family_name', 'patient_last'],
    patient_name: ['name', 'patientname', 'full_name', 'patient_full_name', 'pt_name'],
    patient_gender: ['gender', 'sex', 'gndr'],
    patient_birth_date: ['dob', 'date_of_birth', 'birth_date', 'birthdate', 'patient_dob'],
    patient_phone: ['phone', 'phone_number', 'mobile', 'cell', 'cell_phone', 'patient_phone_number', 'patient_mobile', 'patient_home_phone', 'patient_phone'],
    patient_email: ['email', 'email_address'],
    patient_address_line1: ['address', 'address1', 'address_line1', 'street', 'street_address', 'patient_address1', 'patient_address_1', 'addr_line1'],
    patient_address_line2: ['address2', 'address_line2', 'street2', 'street_address_2', 'patient_address2', 'patient_address_2'],
    patient_city: ['city', 'town'],
    patient_state: ['state', 'province', 'region', 'patient_province'],
    patient_postal_code: ['zip', 'zipcode', 'postal', 'postal_code', 'patient_zip'],
    patient_country: ['country']
  },
  encounter: {
    encounter_id: ['visit_id', 'encounter_identifier', 'encounterid', 'visitid', 'csn', 'encntr_id'],
    encounter_class: ['encounter_type', 'visit_class', 'encounterclass'],
    encounter_start: ['encounter_start_time', 'visit_start', 'visit_start_time', 'admit_time', 'admit_datetime'],
    encounter_location: ['visit_location', 'encounter_room', 'dept_name', 'departmentname', 'department_name', 'location_name', 'location_code', 'facility_id', 'nurse_unit', 'room'],
    encounter_status: ['encounterstate'],
    encounter_practitioner_id: ['encounter_participant_id', 'encounter_practitioner_ids', 'attending_npi', 'attend_prsnl_id', 'attending_provider_id', 'provider_npi'],
    encounter_service_provider_id: ['service_provider_id', 'service_provider_organization_id']
  },
  observation: {
    observation_id: ['obs_id', 'observation_identifier', 'observationid'],
    observation_code: ['obs_code', 'test_code', 'loinc_code', 'observationcode', 'lab_loinc', 'lab_code', 'lab_test_code', 'labordercode'],
    observation_code_system: ['obs_code_system', 'loinc_system'],
    observation_display: ['obs_display', 'test_name', 'observation_name', 'observation_display_name', 'lab_name', 'lab_test_name'],
    observation_value: ['obs_value', 'result_value', 'lab_result', 'lab_value', 'lab_result_value', 'labresultvalue'],
    observation_unit: ['obs_unit', 'result_unit', 'lab_unit', 'lab_result_unit'],
    observation_date: ['obs_date', 'observation_datetime', 'observation_time', 'recorded_datetime', 'lab_result_date', 'result_dt', 'lab_collected_datetime', 'labresultdate'],
    observation_status: ['obs_status', 'result_status', 'lab_result_status']
  },
  medication: {
    medication_id: ['med_id', 'medication_identifier', 'medicationid'],
    medication_code: ['med_code', 'rxnorm_code', 'ndc_code', 'medicationcode'],
    medication_code_system: ['med_code_system', 'rxnorm_system', 'ndc_system'],
    medication_display: ['med_display', 'medication_name', 'drug_name']
  },
  medicationRequest: {
    medication_request_id: ['med_request_id', 'prescription_id', 'order_id'],
    medication_status: ['med_status', 'medication_request_status'],
    medication_authored_on: ['med_authored_on', 'order_date'],
    medication_dose: ['med_dose'],
    medication_dose_unit: ['med_dose_unit', 'dose_unit'],
    medication_route: ['med_route'],
    medication_route_display: ['med_route_display', 'route_display'],
    medication_sig: ['med_sig', 'sig', 'instructions']
  },
  medicationStatement: {
    medication_statement_id: ['med_statement_id', 'medicationstatement_id'],
    medication_statement_status: ['med_statement_status', 'medication_statement_state'],
    medication_statement_category: ['med_statement_category', 'medication_statement_type'],
    medication_statement_medication_code: ['med_statement_code', 'medication_code'],
    medication_statement_medication_code_system: ['med_statement_code_system', 'medication_code_system'],
    medication_statement_medication_display: ['med_statement_display', 'medication_display'],
    medication_statement_subject_id: ['med_statement_subject_id', 'subject_id', 'patient_id'],
    medication_statement_encounter_id: ['med_statement_encounter_id', 'encounter_id'],
    medication_statement_effective_date: ['med_statement_effective_date', 'effective_date'],
    medication_statement_effective_start: ['med_statement_effective_start', 'effective_start'],
    medication_statement_effective_end: ['med_statement_effective_end', 'effective_end'],
    medication_statement_date_asserted: ['med_statement_date_asserted', 'date_asserted'],
    medication_statement_author: ['med_statement_author', 'author_id'],
    medication_statement_information_source: ['med_statement_information_source', 'information_source'],
    medication_statement_reason: ['med_statement_reason', 'reason'],
    medication_statement_note: ['med_statement_note', 'note'],
    medication_statement_dose: ['med_statement_dose', 'dose'],
    medication_statement_dose_unit: ['med_statement_dose_unit', 'dose_unit'],
    medication_statement_route: ['med_statement_route', 'route'],
    medication_statement_route_display: ['med_statement_route_display', 'route_display']
  },
  medicationAdministration: {
    medication_administration_id: ['med_admin_id', 'medicationadministration_id'],
    medication_administration_status: ['med_admin_status', 'status'],
    medication_administration_status_reason: ['med_admin_status_reason', 'status_reason'],
    medication_administration_category: ['med_admin_category', 'category'],
    medication_administration_medication_code: ['med_admin_code', 'medication_code'],
    medication_administration_medication_code_system: ['med_admin_code_system', 'medication_code_system'],
    medication_administration_medication_display: ['med_admin_display', 'medication_display'],
    medication_administration_subject_id: ['med_admin_subject_id', 'subject_id', 'patient_id'],
    medication_administration_encounter_id: ['med_admin_encounter_id', 'encounter_id'],
    medication_administration_occurrence_date: ['med_admin_occurrence_date', 'occurrence_date'],
    medication_administration_occurrence_start: ['med_admin_occurrence_start', 'occurrence_start'],
    medication_administration_occurrence_end: ['med_admin_occurrence_end', 'occurrence_end'],
    medication_administration_recorded: ['med_admin_recorded', 'recorded'],
    medication_administration_is_sub_potent: ['med_admin_is_sub_potent', 'is_sub_potent'],
    medication_administration_sub_potent_reason: ['med_admin_sub_potent_reason', 'sub_potent_reason'],
    medication_administration_performer_actor_id: ['med_admin_performer_actor_id', 'performer_actor_id'],
    medication_administration_performer_function: ['med_admin_performer_function', 'performer_function'],
    medication_administration_reason: ['med_admin_reason', 'reason'],
    medication_administration_request_id: ['med_admin_request_id', 'request_id'],
    medication_administration_device_ids: ['med_admin_device_ids', 'device_ids', 'device_id'],
    medication_administration_note: ['med_admin_note', 'note'],
    medication_administration_based_on_ids: ['med_admin_based_on_ids', 'based_on_ids', 'based_on_id'],
    medication_administration_part_of_ids: ['med_admin_part_of_ids', 'part_of_ids', 'part_of_id'],
    medication_administration_supporting_info_ids: ['med_admin_supporting_info_ids', 'supporting_info_ids', 'supporting_info_id'],
    medication_administration_dose_value: ['med_admin_dose_value', 'dose_value', 'dose'],
    medication_administration_dose_unit: ['med_admin_dose_unit', 'dose_unit'],
    medication_administration_route: ['med_admin_route', 'route'],
    medication_administration_site: ['med_admin_site', 'site'],
    medication_administration_method: ['med_admin_method', 'method'],
    medication_administration_rate_value: ['med_admin_rate_value', 'rate_value'],
    medication_administration_rate_unit: ['med_admin_rate_unit', 'rate_unit']
  },
  medicationDispense: {
    medication_dispense_id: ['med_dispense_id', 'medicationdispense_id'],
    medication_dispense_status: ['med_dispense_status', 'status'],
    medication_dispense_status_changed: ['med_dispense_status_changed', 'status_changed'],
    medication_dispense_category: ['med_dispense_category', 'category'],
    medication_dispense_medication_code: ['med_dispense_code', 'medication_code'],
    medication_dispense_medication_code_system: ['med_dispense_code_system', 'medication_code_system'],
    medication_dispense_medication_display: ['med_dispense_display', 'medication_display'],
    medication_dispense_subject_id: ['med_dispense_subject_id', 'subject_id', 'patient_id'],
    medication_dispense_encounter_id: ['med_dispense_encounter_id', 'encounter_id'],
    medication_dispense_location: ['med_dispense_location', 'location'],
    medication_dispense_quantity_value: ['med_dispense_quantity_value', 'quantity_value'],
    medication_dispense_quantity_unit: ['med_dispense_quantity_unit', 'quantity_unit'],
    medication_dispense_days_supply_value: ['med_dispense_days_supply_value', 'days_supply_value'],
    medication_dispense_days_supply_unit: ['med_dispense_days_supply_unit', 'days_supply_unit'],
    medication_dispense_recorded: ['med_dispense_recorded', 'recorded'],
    medication_dispense_when_prepared: ['med_dispense_when_prepared', 'when_prepared'],
    medication_dispense_when_handed_over: ['med_dispense_when_handed_over', 'when_handed_over'],
    medication_dispense_destination: ['med_dispense_destination', 'destination'],
    medication_dispense_authorizing_prescription_ids: ['med_dispense_authorizing_prescription_ids', 'authorizing_prescription_ids', 'authorizing_prescription_id'],
    medication_dispense_receiver_ids: ['med_dispense_receiver_ids', 'receiver_ids', 'receiver_id'],
    medication_dispense_note: ['med_dispense_note', 'note'],
    medication_dispense_rendered_dosage_instruction: ['med_dispense_rendered_dosage_instruction', 'rendered_dosage_instruction'],
    medication_dispense_dosage_instruction: ['med_dispense_dosage_instruction', 'dosage_instruction'],
    medication_dispense_substitution_was_substituted: ['med_dispense_substitution_was_substituted', 'substitution_was_substituted'],
    medication_dispense_substitution_type: ['med_dispense_substitution_type', 'substitution_type'],
    medication_dispense_substitution_reason: ['med_dispense_substitution_reason', 'substitution_reason'],
    medication_dispense_substitution_responsible_party: ['med_dispense_substitution_responsible_party', 'substitution_responsible_party'],
    medication_dispense_supporting_info_ids: ['med_dispense_supporting_info_ids', 'supporting_info_ids', 'supporting_info_id'],
    medication_dispense_part_of_ids: ['med_dispense_part_of_ids', 'part_of_ids', 'part_of_id'],
    medication_dispense_based_on_ids: ['med_dispense_based_on_ids', 'based_on_ids', 'based_on_id'],
    medication_dispense_performer_actor_id: ['med_dispense_performer_actor_id', 'performer_actor_id'],
    medication_dispense_performer_function: ['med_dispense_performer_function', 'performer_function'],
    medication_dispense_type: ['med_dispense_type', 'type'],
    medication_dispense_event_history_ids: ['med_dispense_event_history_ids', 'event_history_ids', 'event_history_id']
  },
  deviceDispense: {
    device_dispense_id: ['device_dispense_identifier', 'devicedispense_id', 'devicedispenseid'],
    device_dispense_based_on_ids: ['based_on_ids', 'device_dispense_based_on_ids'],
    device_dispense_part_of_ids: ['part_of_ids', 'device_dispense_part_of_ids'],
    device_dispense_status: ['status', 'device_dispense_status'],
    device_dispense_status_reason_code: ['status_reason_code', 'device_dispense_status_reason_code'],
    device_dispense_status_reason_reference_id: ['status_reason_reference_id', 'device_dispense_status_reason_reference_id'],
    device_dispense_category: ['category', 'device_dispense_category'],
    device_dispense_device_id: ['device_id', 'device_dispense_device_id'],
    device_dispense_device_code: ['device_code', 'device_dispense_device_code'],
    device_dispense_subject_id: ['subject_id', 'device_dispense_subject_id', 'patient_id'],
    device_dispense_receiver_id: ['receiver_id', 'device_dispense_receiver_id'],
    device_dispense_encounter_id: ['encounter_id', 'device_dispense_encounter_id'],
    device_dispense_supporting_information_ids: ['supporting_information_ids', 'device_dispense_supporting_information_ids'],
    device_dispense_performer_function: ['performer_function', 'device_dispense_performer_function'],
    device_dispense_performer_actor_id: ['performer_actor_id', 'device_dispense_performer_actor_id'],
    device_dispense_location_id: ['location_id', 'device_dispense_location_id'],
    device_dispense_type: ['type', 'device_dispense_type'],
    device_dispense_quantity_value: ['quantity_value', 'device_dispense_quantity_value'],
    device_dispense_quantity_unit: ['quantity_unit', 'device_dispense_quantity_unit'],
    device_dispense_prepared_date: ['prepared_date', 'device_dispense_prepared_date'],
    device_dispense_when_handed_over: ['when_handed_over', 'device_dispense_when_handed_over'],
    device_dispense_destination_id: ['destination_id', 'device_dispense_destination_id'],
    device_dispense_note: ['note', 'device_dispense_note'],
    device_dispense_usage_instruction: ['usage_instruction', 'device_dispense_usage_instruction'],
    device_dispense_event_history_ids: ['event_history_ids', 'device_dispense_event_history_ids']
  },
  deviceRequest: {
    device_request_id: ['device_request_identifier', 'devicerequest_id', 'devicerequestid'],
    device_request_status: ['status', 'device_request_status'],
    device_request_intent: ['intent', 'device_request_intent'],
    device_request_priority: ['priority', 'device_request_priority'],
    device_request_do_not_perform: ['do_not_perform', 'device_request_do_not_perform'],
    device_request_device_code: ['device_code', 'device_request_device_code'],
    device_request_device_reference_id: ['device_reference_id', 'device_request_device_reference_id', 'device_id'],
    device_request_subject_id: ['subject_id', 'device_request_subject_id', 'patient_id'],
    device_request_encounter_id: ['encounter_id', 'device_request_encounter_id'],
    device_request_occurrence_date_time: ['occurrence_date_time', 'occurrence_datetime', 'occurrence_date'],
    device_request_occurrence_start: ['occurrence_start', 'device_request_occurrence_start'],
    device_request_occurrence_end: ['occurrence_end', 'device_request_occurrence_end'],
    device_request_occurrence_timing: ['occurrence_timing', 'device_request_occurrence_timing'],
    device_request_authored_on: ['authored_on', 'device_request_authored_on'],
    device_request_requester_id: ['requester_id', 'device_request_requester_id'],
    device_request_performer_id: ['performer_id', 'device_request_performer_id'],
    device_request_reason_ids: ['reason_ids', 'reason_id', 'reason', 'device_request_reason_ids'],
    device_request_as_needed: ['as_needed', 'device_request_as_needed'],
    device_request_as_needed_for: ['as_needed_for', 'device_request_as_needed_for'],
    device_request_insurance_ids: ['insurance_ids', 'insurance_id', 'device_request_insurance_ids'],
    device_request_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id', 'device_request_supporting_info_ids'],
    device_request_note: ['note', 'device_request_note'],
    device_request_relevant_history_ids: ['relevant_history_ids', 'relevant_history_id', 'device_request_relevant_history_ids'],
    device_request_instantiates_canonical: ['instantiates_canonical', 'device_request_instantiates_canonical'],
    device_request_instantiates_uri: ['instantiates_uri', 'device_request_instantiates_uri'],
    device_request_based_on_ids: ['based_on_ids', 'based_on_id', 'device_request_based_on_ids'],
    device_request_replaces_ids: ['replaces_ids', 'replaces_id', 'device_request_replaces_ids'],
    device_request_group_identifier: ['group_identifier', 'device_request_group_identifier'],
    device_request_quantity_value: ['quantity_value', 'quantity', 'device_request_quantity_value'],
    device_request_parameter_code: ['parameter_code', 'device_request_parameter_code'],
    device_request_parameter_value_code: ['parameter_value_code', 'parameter_value_codeable', 'device_request_parameter_value_code'],
    device_request_parameter_value_quantity_value: ['parameter_value_quantity_value', 'parameter_quantity_value', 'device_request_parameter_value_quantity_value'],
    device_request_parameter_value_quantity_unit: ['parameter_value_quantity_unit', 'parameter_quantity_unit', 'device_request_parameter_value_quantity_unit'],
    device_request_parameter_value_boolean: ['parameter_value_boolean', 'device_request_parameter_value_boolean']
  },
  deviceUsage: {
    device_usage_id: ['device_usage_identifier', 'deviceusage_id', 'deviceusageid'],
    device_usage_based_on_ids: ['based_on_ids', 'device_usage_based_on_ids'],
    device_usage_status: ['status', 'device_usage_status'],
    device_usage_category: ['category', 'device_usage_category'],
    device_usage_patient_id: ['patient_id', 'device_usage_patient_id'],
    device_usage_derived_from_ids: ['derived_from_ids', 'device_usage_derived_from_ids'],
    device_usage_context_id: ['context_id', 'device_usage_context_id'],
    device_usage_timing_timing: ['timing_timing', 'device_usage_timing_timing'],
    device_usage_timing_start: ['timing_start', 'device_usage_timing_start'],
    device_usage_timing_end: ['timing_end', 'device_usage_timing_end'],
    device_usage_timing_date_time: ['timing_date_time', 'device_usage_timing_date_time'],
    device_usage_date_asserted: ['date_asserted', 'device_usage_date_asserted'],
    device_usage_usage_status: ['usage_status', 'device_usage_usage_status'],
    device_usage_usage_reason: ['usage_reason', 'device_usage_usage_reason'],
    device_usage_adherence_code: ['adherence_code', 'device_usage_adherence_code'],
    device_usage_adherence_reason: ['adherence_reason', 'device_usage_adherence_reason'],
    device_usage_information_source_id: ['information_source_id', 'device_usage_information_source_id'],
    device_usage_device_code: ['device_code', 'device_usage_device_code'],
    device_usage_device_reference_id: ['device_reference_id', 'device_usage_device_reference_id', 'device_id'],
    device_usage_reason_ids: ['reason_ids', 'reason_id', 'reason', 'device_usage_reason_ids'],
    device_usage_body_site_id: ['body_site_id', 'device_usage_body_site_id'],
    device_usage_note: ['note', 'device_usage_note']
  },
  encounterHistory: {
    encounter_history_id: ['encounter_history_identifier', 'encounterhistory_id', 'encounterhistoryid'],
    encounter_history_encounter_id: ['encounter_id', 'encounter_history_encounter_id'],
    encounter_history_status: ['status', 'encounter_history_status'],
    encounter_history_class: ['class', 'encounter_history_class'],
    encounter_history_type: ['type', 'encounter_history_type'],
    encounter_history_service_type: ['service_type', 'encounter_history_service_type'],
    encounter_history_service_type_reference_ids: ['service_type_reference_ids', 'encounter_history_service_type_reference_ids'],
    encounter_history_subject_id: ['subject_id', 'patient_id', 'encounter_history_subject_id'],
    encounter_history_subject_status: ['subject_status', 'encounter_history_subject_status'],
    encounter_history_actual_start: ['actual_start', 'encounter_history_actual_start'],
    encounter_history_actual_end: ['actual_end', 'encounter_history_actual_end'],
    encounter_history_planned_start_date: ['planned_start_date', 'encounter_history_planned_start_date'],
    encounter_history_planned_end_date: ['planned_end_date', 'encounter_history_planned_end_date'],
    encounter_history_length_value: ['length_value', 'encounter_history_length_value'],
    encounter_history_length_unit: ['length_unit', 'encounter_history_length_unit'],
    encounter_history_length_system: ['length_system', 'encounter_history_length_system'],
    encounter_history_length_code: ['length_code', 'encounter_history_length_code'],
    encounter_history_location_id: ['location_id', 'encounter_history_location_id'],
    encounter_history_location_form: ['location_form', 'encounter_history_location_form']
  },
  flag: {
    flag_id: ['flag_identifier', 'flagid', 'flag_id'],
    flag_status: ['status', 'flag_status'],
    flag_category: ['category', 'flag_category'],
    flag_code: ['code', 'flag_code'],
    flag_subject_id: ['subject_id', 'flag_subject_id', 'patient_id'],
    flag_period_start: ['period_start', 'flag_period_start'],
    flag_period_end: ['period_end', 'flag_period_end'],
    flag_encounter_id: ['encounter_id', 'flag_encounter_id'],
    flag_author_id: ['author_id', 'flag_author_id']
  },
  list: {
    list_id: ['list_identifier', 'listid', 'list_id'],
    list_status: ['status', 'list_status'],
    list_mode: ['mode', 'list_mode'],
    list_title: ['title', 'list_title'],
    list_code: ['code', 'list_code'],
    list_subject_ids: ['subject_ids', 'subject_id', 'list_subject_ids'],
    list_encounter_id: ['encounter_id', 'list_encounter_id'],
    list_date: ['date', 'list_date'],
    list_source_id: ['source_id', 'list_source_id'],
    list_ordered_by: ['ordered_by', 'list_ordered_by'],
    list_note: ['note', 'list_note'],
    list_entry_flag: ['entry_flag', 'list_entry_flag'],
    list_entry_deleted: ['entry_deleted', 'list_entry_deleted'],
    list_entry_date: ['entry_date', 'list_entry_date'],
    list_entry_item_id: ['entry_item_id', 'list_entry_item_id'],
    list_empty_reason: ['empty_reason', 'list_empty_reason']
  },
  nutritionIntake: {
    nutrition_intake_id: ['nutrition_intake_identifier', 'nutritionintake_id', 'nutritionintakeid'],
    nutrition_intake_status: ['status', 'nutrition_intake_status'],
    nutrition_intake_status_reason: ['status_reason', 'nutrition_intake_status_reason'],
    nutrition_intake_code: ['code', 'nutrition_intake_code'],
    nutrition_intake_subject_id: ['subject_id', 'nutrition_intake_subject_id', 'patient_id'],
    nutrition_intake_encounter_id: ['encounter_id', 'nutrition_intake_encounter_id'],
    nutrition_intake_occurrence_date_time: ['occurrence_date_time', 'occurrence_datetime', 'occurrence_date'],
    nutrition_intake_occurrence_start: ['occurrence_start', 'nutrition_intake_occurrence_start'],
    nutrition_intake_occurrence_end: ['occurrence_end', 'nutrition_intake_occurrence_end'],
    nutrition_intake_recorded: ['recorded', 'nutrition_intake_recorded'],
    nutrition_intake_reported_boolean: ['reported_boolean', 'nutrition_intake_reported_boolean'],
    nutrition_intake_reported_reference_id: ['reported_reference_id', 'nutrition_intake_reported_reference_id'],
    nutrition_intake_instantiates_canonical: ['instantiates_canonical', 'nutrition_intake_instantiates_canonical'],
    nutrition_intake_instantiates_uri: ['instantiates_uri', 'nutrition_intake_instantiates_uri'],
    nutrition_intake_based_on_ids: ['based_on_ids', 'based_on_id', 'nutrition_intake_based_on_ids'],
    nutrition_intake_part_of_ids: ['part_of_ids', 'part_of_id', 'nutrition_intake_part_of_ids'],
    nutrition_intake_consumed_type: ['consumed_type', 'nutrition_intake_consumed_type'],
    nutrition_intake_consumed_product_code: ['consumed_product_code', 'nutrition_intake_consumed_product_code'],
    nutrition_intake_consumed_product_reference_id: ['consumed_product_reference_id', 'nutrition_intake_consumed_product_reference_id'],
    nutrition_intake_consumed_amount_value: ['consumed_amount_value', 'nutrition_intake_consumed_amount_value'],
    nutrition_intake_consumed_amount_unit: ['consumed_amount_unit', 'nutrition_intake_consumed_amount_unit'],
    nutrition_intake_consumed_not_consumed: ['consumed_not_consumed', 'nutrition_intake_consumed_not_consumed'],
    nutrition_intake_consumed_not_consumed_reason: ['consumed_not_consumed_reason', 'nutrition_intake_consumed_not_consumed_reason'],
    nutrition_intake_ingredient_nutrient_code: ['ingredient_nutrient_code', 'nutrition_intake_ingredient_nutrient_code'],
    nutrition_intake_ingredient_nutrient_reference_id: ['ingredient_nutrient_reference_id', 'nutrition_intake_ingredient_nutrient_reference_id'],
    nutrition_intake_ingredient_amount_value: ['ingredient_amount_value', 'nutrition_intake_ingredient_amount_value'],
    nutrition_intake_ingredient_amount_unit: ['ingredient_amount_unit', 'nutrition_intake_ingredient_amount_unit'],
    nutrition_intake_performer_function: ['performer_function', 'nutrition_intake_performer_function'],
    nutrition_intake_performer_actor_id: ['performer_actor_id', 'nutrition_intake_performer_actor_id'],
    nutrition_intake_location_id: ['location_id', 'nutrition_intake_location_id'],
    nutrition_intake_derived_from_ids: ['derived_from_ids', 'derived_from_id', 'nutrition_intake_derived_from_ids'],
    nutrition_intake_reason_ids: ['reason_ids', 'reason_id', 'nutrition_intake_reason_ids'],
    nutrition_intake_note: ['note', 'nutrition_intake_note']
  },
  nutritionOrder: {
    nutrition_order_id: ['nutrition_order_identifier', 'nutritionorder_id', 'nutritionorderid', 'nutrition_order_id'],
    nutrition_order_status: ['status', 'nutrition_order_status'],
    nutrition_order_intent: ['intent', 'nutrition_order_intent'],
    nutrition_order_priority: ['priority', 'nutrition_order_priority'],
    nutrition_order_subject_id: ['subject_id', 'nutrition_order_subject_id', 'patient_id'],
    nutrition_order_encounter_id: ['encounter_id', 'nutrition_order_encounter_id'],
    nutrition_order_date_time: ['date_time', 'nutrition_order_date_time', 'nutrition_order_datetime'],
    nutrition_order_orderer_id: ['orderer_id', 'nutrition_order_orderer_id'],
    nutrition_order_supporting_information_ids: ['supporting_information_ids', 'supporting_information_id', 'nutrition_order_supporting_information_ids'],
    nutrition_order_based_on_ids: ['based_on_ids', 'based_on_id', 'nutrition_order_based_on_ids'],
    nutrition_order_instantiates_canonical: ['instantiates_canonical', 'nutrition_order_instantiates_canonical'],
    nutrition_order_instantiates_uri: ['instantiates_uri', 'nutrition_order_instantiates_uri'],
    nutrition_order_instantiates: ['instantiates', 'nutrition_order_instantiates'],
    nutrition_order_group_identifier: ['group_identifier', 'nutrition_order_group_identifier'],
    nutrition_order_performer_concept: ['performer_concept', 'nutrition_order_performer_concept'],
    nutrition_order_performer_reference_ids: ['performer_reference_ids', 'performer_reference_id', 'nutrition_order_performer_reference_ids'],
    nutrition_order_allergy_intolerance_ids: ['allergy_intolerance_ids', 'allergy_intolerance_id', 'nutrition_order_allergy_intolerance_ids'],
    nutrition_order_food_preference_modifier: ['food_preference_modifier', 'nutrition_order_food_preference_modifier'],
    nutrition_order_exclude_food_modifier: ['exclude_food_modifier', 'nutrition_order_exclude_food_modifier'],
    nutrition_order_outside_food_allowed: ['outside_food_allowed', 'nutrition_order_outside_food_allowed'],
    nutrition_order_oral_diet_type: ['oral_diet_type', 'nutrition_order_oral_diet_type'],
    nutrition_order_oral_diet_schedule_timing: ['oral_diet_schedule_timing', 'nutrition_order_oral_diet_schedule_timing'],
    nutrition_order_oral_diet_as_needed: ['oral_diet_as_needed', 'nutrition_order_oral_diet_as_needed'],
    nutrition_order_oral_diet_as_needed_for: ['oral_diet_as_needed_for', 'nutrition_order_oral_diet_as_needed_for'],
    nutrition_order_oral_diet_instruction: ['oral_diet_instruction', 'nutrition_order_oral_diet_instruction'],
    nutrition_order_supplement_type_code: ['supplement_type_code', 'nutrition_order_supplement_type_code'],
    nutrition_order_supplement_type_reference_id: ['supplement_type_reference_id', 'nutrition_order_supplement_type_reference_id'],
    nutrition_order_supplement_product_name: ['supplement_product_name', 'nutrition_order_supplement_product_name'],
    nutrition_order_supplement_schedule_timing: ['supplement_schedule_timing', 'nutrition_order_supplement_schedule_timing'],
    nutrition_order_supplement_as_needed: ['supplement_as_needed', 'nutrition_order_supplement_as_needed'],
    nutrition_order_supplement_as_needed_for: ['supplement_as_needed_for', 'nutrition_order_supplement_as_needed_for'],
    nutrition_order_supplement_quantity_value: ['supplement_quantity_value', 'nutrition_order_supplement_quantity_value'],
    nutrition_order_supplement_quantity_unit: ['supplement_quantity_unit', 'nutrition_order_supplement_quantity_unit'],
    nutrition_order_supplement_instruction: ['supplement_instruction', 'nutrition_order_supplement_instruction'],
    nutrition_order_enteral_base_formula_code: ['enteral_base_formula_code', 'nutrition_order_enteral_base_formula_code'],
    nutrition_order_enteral_base_formula_reference_id: ['enteral_base_formula_reference_id', 'nutrition_order_enteral_base_formula_reference_id'],
    nutrition_order_enteral_base_formula_product_name: ['enteral_base_formula_product_name', 'nutrition_order_enteral_base_formula_product_name'],
    nutrition_order_enteral_route_of_administration: ['enteral_route_of_administration', 'nutrition_order_enteral_route_of_administration'],
    nutrition_order_enteral_caloric_density_value: ['enteral_caloric_density_value', 'nutrition_order_enteral_caloric_density_value'],
    nutrition_order_enteral_caloric_density_unit: ['enteral_caloric_density_unit', 'nutrition_order_enteral_caloric_density_unit'],
    nutrition_order_enteral_administration_instruction: ['enteral_administration_instruction', 'nutrition_order_enteral_administration_instruction'],
    nutrition_order_note: ['note', 'nutrition_order_note']
  },
  riskAssessment: {
    risk_assessment_id: ['risk_assessment_identifier', 'riskassessment_id', 'riskassessmentid', 'risk_assessment_id'],
    risk_assessment_status: ['status', 'risk_assessment_status'],
    risk_assessment_method: ['method', 'risk_assessment_method'],
    risk_assessment_code: ['code', 'risk_assessment_code'],
    risk_assessment_subject_id: ['subject_id', 'risk_assessment_subject_id', 'patient_id'],
    risk_assessment_encounter_id: ['encounter_id', 'risk_assessment_encounter_id'],
    risk_assessment_occurrence_date_time: ['occurrence_date_time', 'occurrence_datetime', 'risk_assessment_occurrence_date_time'],
    risk_assessment_occurrence_start: ['occurrence_start', 'risk_assessment_occurrence_start'],
    risk_assessment_occurrence_end: ['occurrence_end', 'risk_assessment_occurrence_end'],
    risk_assessment_based_on_id: ['based_on_id', 'risk_assessment_based_on_id'],
    risk_assessment_parent_id: ['parent_id', 'risk_assessment_parent_id'],
    risk_assessment_condition_id: ['condition_id', 'risk_assessment_condition_id'],
    risk_assessment_performer_id: ['performer_id', 'risk_assessment_performer_id'],
    risk_assessment_reason_ids: ['reason_ids', 'reason_id', 'risk_assessment_reason_ids'],
    risk_assessment_basis_ids: ['basis_ids', 'basis_id', 'risk_assessment_basis_ids'],
    risk_assessment_prediction_outcome: ['prediction_outcome', 'risk_assessment_prediction_outcome'],
    risk_assessment_prediction_probability_decimal: ['prediction_probability_decimal', 'risk_assessment_prediction_probability_decimal'],
    risk_assessment_prediction_probability_range_low_value: ['prediction_probability_range_low_value', 'risk_assessment_prediction_probability_range_low_value'],
    risk_assessment_prediction_probability_range_low_unit: ['prediction_probability_range_low_unit', 'risk_assessment_prediction_probability_range_low_unit'],
    risk_assessment_prediction_probability_range_high_value: ['prediction_probability_range_high_value', 'risk_assessment_prediction_probability_range_high_value'],
    risk_assessment_prediction_probability_range_high_unit: ['prediction_probability_range_high_unit', 'risk_assessment_prediction_probability_range_high_unit'],
    risk_assessment_prediction_qualitative_risk: ['prediction_qualitative_risk', 'risk_assessment_prediction_qualitative_risk'],
    risk_assessment_prediction_relative_risk: ['prediction_relative_risk', 'risk_assessment_prediction_relative_risk'],
    risk_assessment_prediction_when_start: ['prediction_when_start', 'risk_assessment_prediction_when_start'],
    risk_assessment_prediction_when_end: ['prediction_when_end', 'risk_assessment_prediction_when_end'],
    risk_assessment_prediction_when_range_low_value: ['prediction_when_range_low_value', 'risk_assessment_prediction_when_range_low_value'],
    risk_assessment_prediction_when_range_low_unit: ['prediction_when_range_low_unit', 'risk_assessment_prediction_when_range_low_unit'],
    risk_assessment_prediction_when_range_high_value: ['prediction_when_range_high_value', 'risk_assessment_prediction_when_range_high_value'],
    risk_assessment_prediction_when_range_high_unit: ['prediction_when_range_high_unit', 'risk_assessment_prediction_when_range_high_unit'],
    risk_assessment_prediction_rationale: ['prediction_rationale', 'risk_assessment_prediction_rationale'],
    risk_assessment_mitigation: ['mitigation', 'risk_assessment_mitigation'],
    risk_assessment_note: ['note', 'risk_assessment_note']
  },
  capabilityStatement: {
    capability_statement_id: ['capability_statement_id', 'capabilitystatement_id'],
    capability_statement_url: ['capability_url', 'url'],
    capability_statement_identifier: ['identifier'],
    capability_statement_version: ['version'],
    capability_statement_name: ['name'],
    capability_statement_title: ['title'],
    capability_statement_status: ['status'],
    capability_statement_date: ['date'],
    capability_statement_publisher: ['publisher'],
    capability_statement_kind: ['kind'],
    capability_statement_fhir_version: ['fhir_version', 'fhirversion'],
    capability_statement_format: ['format'],
    capability_statement_description: ['description'],
    capability_statement_implementation_url: ['implementation_url'],
    capability_statement_implementation_description: ['implementation_description'],
    capability_statement_software_name: ['software_name'],
    capability_statement_software_version: ['software_version'],
    capability_statement_software_release_date: ['software_release_date'],
    capability_statement_rest_mode: ['rest_mode'],
    capability_statement_rest_documentation: ['rest_documentation']
  },
  operationOutcome: {
    operation_outcome_id: ['operation_outcome_id', 'operationoutcome_id'],
    operation_outcome_severity: ['severity'],
    operation_outcome_code: ['code'],
    operation_outcome_details_system: ['details_system'],
    operation_outcome_details_code: ['details_code'],
    operation_outcome_details_display: ['details_display'],
    operation_outcome_diagnostics: ['diagnostics'],
    operation_outcome_location: ['location'],
    operation_outcome_expression: ['expression']
  },
  parameters: {
    parameter_name: ['name', 'param_name'],
    parameter_value: ['value', 'param_value'],
    parameter_value_string: ['value_string'],
    parameter_value_code: ['value_code'],
    parameter_value_boolean: ['value_boolean', 'value_bool'],
    parameter_value_date: ['value_date'],
    parameter_value_datetime: ['value_datetime', 'value_date_time'],
    parameter_value_integer: ['value_integer', 'value_int'],
    parameter_value_decimal: ['value_decimal'],
    parameter_value_uri: ['value_uri'],
    parameter_value_reference: ['value_reference']
  },
  procedure: {
    procedure_id: ['proc_id', 'procedure_identifier', 'procedureid'],
    procedure_status: ['proc_status', 'procedure_status'],
    procedure_category: ['proc_category', 'procedure_category'],
    procedure_code: ['proc_code', 'procedure_code', 'procedure_cpt', 'procedurecpt', 'cpt'],
    procedure_code_system: ['proc_code_system', 'procedure_code_system'],
    procedure_display: ['proc_display', 'procedure_display', 'procedure_name', 'procedure_desc', 'procedure_description', 'procedure_text'],
    procedure_subject_id: ['proc_subject_id', 'subject_id', 'patient_id'],
    procedure_encounter_id: ['proc_encounter_id', 'encounter_id'],
    procedure_occurrence_date: ['proc_occurrence_date', 'occurrence_date'],
    procedure_occurrence_start: ['proc_occurrence_start', 'occurrence_start'],
    procedure_occurrence_end: ['proc_occurrence_end', 'occurrence_end'],
    procedure_recorded: ['proc_recorded', 'recorded'],
    procedure_performer_id: ['proc_performer_id', 'performer_id'],
    procedure_location: ['proc_location', 'location'],
    procedure_reason: ['proc_reason', 'reason'],
    procedure_body_site: ['proc_body_site', 'body_site'],
    procedure_note: ['proc_note', 'note']
  },
  condition: {
    condition_id: ['cond_id', 'condition_identifier', 'conditionid'],
    condition_clinical_status: ['cond_clinical_status', 'clinical_status'],
    condition_verification_status: ['cond_verification_status', 'verification_status'],
    condition_category: ['cond_category', 'condition_category'],
    condition_severity: ['cond_severity', 'severity'],
    condition_code: ['cond_code', 'condition_code', 'dx_code', 'dx_icd10', 'diagnosis_code', 'primary_dx_code', 'dxcode'],
    condition_code_system: ['cond_code_system', 'condition_code_system'],
    condition_display: ['cond_display', 'condition_display', 'condition_name', 'dx_desc', 'diagnosis_text', 'primary_dx_desc', 'dxdescription'],
    condition_body_site: ['cond_body_site', 'body_site'],
    condition_subject_id: ['cond_subject_id', 'subject_id', 'patient_id'],
    condition_encounter_id: ['cond_encounter_id', 'encounter_id'],
    condition_onset_date: ['cond_onset_date', 'onset_date'],
    condition_onset_start: ['cond_onset_start', 'onset_start'],
    condition_onset_end: ['cond_onset_end', 'onset_end'],
    condition_onset_text: ['cond_onset_text', 'onset_text'],
    condition_abatement_date: ['cond_abatement_date', 'abatement_date'],
    condition_abatement_start: ['cond_abatement_start', 'abatement_start'],
    condition_abatement_end: ['cond_abatement_end', 'abatement_end'],
    condition_abatement_text: ['cond_abatement_text', 'abatement_text'],
    condition_recorded_date: ['cond_recorded_date', 'recorded_date'],
    condition_note: ['cond_note', 'note']
  },
  appointment: {
    appointment_id: ['appt_id', 'appointment_identifier', 'appointmentid', 'booking_id', 'appointmentid'],
    appointment_status: ['appt_status', 'status', 'appointment_status', 'appointmentstatus'],
    appointment_description: ['appt_description', 'description', 'visit_type'],
    appointment_start: ['appt_start', 'start', 'appointment_start', 'appointmentdate', 'appt_datetime', 'appointment_start_time', 'start_time'],
    appointment_end: ['appt_end', 'end', 'appointment_end', 'appointment_end_time'],
    appointment_minutes_duration: ['appt_minutes_duration', 'minutes_duration', 'duration_minutes'],
    appointment_created: ['appt_created', 'created', 'created_time_utc', 'created_time'],
    appointment_cancellation_date: ['appt_cancellation_date', 'cancellation_date'],
    appointment_cancellation_reason_display: ['cancellation_reason', 'appointment_cancellation_reason'],
    appointment_cancellation_reason_code: ['cancellation_reason_type', 'appointment_cancellation_reason_type'],
    appointment_cancellation_reason_system: ['cancellation_reason_system'],
    appointment_subject_id: ['appt_subject_id', 'subject_id', 'patient_id', 'developer_patient_id'],
    appointment_location_phone_number: ['location_phone_number'],
    appointment_location_phone_extension: ['location_phone_extension'],
    appointment_waiting_room_path: ['waiting_room_path'],
    appointment_confirmation_type: ['confirmation_type'],
    appointment_last_modified: ['last_modified_time_utc', 'last_modified_time'],
    appointment_provider_location_id: ['provider_location_id'],
    appointment_practice_id: ['practice_id'],
    appointment_visit_reason_id: ['visit_reason_id'],
    appointment_patient_type: ['patient_type'],
    appointment_is_provider_resource: ['is_provider_resource'],
    appointment_participant_id: ['appt_participant_id', 'participant_id'],
    appointment_participant_status: ['appt_participant_status', 'participant_status'],
    appointment_note: ['appt_note', 'note', 'notes']
  },
  appointmentResponse: {
    appointment_response_id: ['appointment_response_identifier', 'appointmentresponse_id', 'appointmentresponseid'],
    appointment_response_appointment_id: ['appointment_id', 'appointment_identifier', 'appointment_ref_id'],
    appointment_response_proposed_new_time: ['proposed_new_time', 'counter_proposal', 'counter_proposed'],
    appointment_response_start: ['appointment_response_start', 'start'],
    appointment_response_end: ['appointment_response_end', 'end'],
    appointment_response_participant_type: ['participant_type', 'participant_role', 'appointment_response_participant_type'],
    appointment_response_actor_id: ['actor_id', 'participant_id', 'appointment_response_actor_id'],
    appointment_response_participant_status: ['participant_status', 'appointment_response_status'],
    appointment_response_comment: ['comment', 'note', 'appointment_response_comment'],
    appointment_response_recurring: ['recurring', 'recurrence', 'is_recurring'],
    appointment_response_occurrence_date: ['occurrence_date', 'appointment_response_occurrence_date'],
    appointment_response_recurrence_id: ['recurrence_id', 'appointment_response_recurrence_id']
  },
  claim: {
    claim_id: ['claim_identifier', 'claimid', 'claim_number'],
    claim_status: ['status', 'claim_status'],
    claim_type: ['type', 'claim_type'],
    claim_sub_type: ['sub_type', 'claim_sub_type'],
    claim_use: ['use', 'claim_use'],
    claim_patient_id: ['patient_id', 'claim_patient_id'],
    claim_billable_start: ['billable_start', 'claim_billable_start', 'claim_period_start'],
    claim_billable_end: ['billable_end', 'claim_billable_end', 'claim_period_end'],
    claim_created: ['created', 'claim_created'],
    claim_enterer_id: ['enterer_id', 'claim_enterer_id'],
    claim_insurer_id: ['insurer_id', 'claim_insurer_id'],
    claim_provider_id: ['provider_id', 'claim_provider_id'],
    claim_priority: ['priority', 'claim_priority'],
    claim_funds_reserve: ['funds_reserve', 'claim_funds_reserve'],
    claim_referral_id: ['referral_id', 'claim_referral_id'],
    claim_facility_id: ['facility_id', 'claim_facility_id'],
    claim_prescription_id: ['prescription_id', 'claim_prescription_id'],
    claim_original_prescription_id: ['original_prescription_id', 'claim_original_prescription_id'],
    claim_drg: ['diagnosis_related_group', 'claim_drg'],
    claim_accident_date: ['accident_date', 'claim_accident_date'],
    claim_accident_type: ['accident_type', 'claim_accident_type'],
    claim_patient_paid_value: ['patient_paid', 'patient_paid_value', 'claim_patient_paid_value'],
    claim_patient_paid_currency: ['patient_paid_currency', 'claim_patient_paid_currency'],
    claim_total_value: ['total_value', 'claim_total_value'],
    claim_total_currency: ['total_currency', 'claim_total_currency'],
    claim_item_sequence: ['item_sequence', 'claim_item_sequence'],
    claim_item_product_or_service: ['item_product_or_service', 'claim_item_product_or_service'],
    claim_item_quantity: ['item_quantity', 'claim_item_quantity'],
    claim_item_unit_price: ['item_unit_price', 'claim_item_unit_price'],
    claim_item_net: ['item_net', 'claim_item_net'],
    claim_item_patient_paid: ['item_patient_paid', 'claim_item_patient_paid'],
    claim_item_location_id: ['item_location_id', 'claim_item_location_id']
  },
  claimResponse: {
    claim_response_id: ['claim_response_identifier', 'claimresponse_id', 'claimresponseid'],
    claim_response_status: ['status', 'claim_response_status'],
    claim_response_type: ['type', 'claim_response_type'],
    claim_response_sub_type: ['sub_type', 'claim_response_sub_type'],
    claim_response_use: ['use', 'claim_response_use'],
    claim_response_patient_id: ['patient_id', 'claim_response_patient_id'],
    claim_response_created: ['created', 'claim_response_created'],
    claim_response_insurer_id: ['insurer_id', 'claim_response_insurer_id'],
    claim_response_requestor_id: ['requestor_id', 'claim_response_requestor_id'],
    claim_response_request_id: ['request_id', 'claim_response_request_id'],
    claim_response_outcome: ['outcome', 'claim_response_outcome'],
    claim_response_disposition: ['disposition', 'claim_response_disposition'],
    claim_response_pre_auth_ref: ['pre_auth_ref', 'claim_response_pre_auth_ref'],
    claim_response_pre_auth_start: ['pre_auth_start', 'claim_response_pre_auth_start'],
    claim_response_pre_auth_end: ['pre_auth_end', 'claim_response_pre_auth_end'],
    claim_response_payee_type: ['payee_type', 'claim_response_payee_type'],
    claim_response_total_value: ['total_value', 'claim_response_total_value'],
    claim_response_total_currency: ['total_currency', 'claim_response_total_currency'],
    claim_response_item_sequence: ['item_sequence', 'claim_response_item_sequence'],
    claim_response_item_category: ['item_category', 'claim_response_item_category'],
    claim_response_item_amount: ['item_amount', 'claim_response_item_amount']
  },
  composition: {
    composition_id: ['composition_identifier', 'compositionid', 'document_id'],
    composition_status: ['status', 'composition_status'],
    composition_type: ['type', 'composition_type'],
    composition_title: ['title', 'composition_title'],
    composition_subject_id: ['subject_id', 'composition_subject_id', 'patient_id'],
    composition_encounter_id: ['encounter_id', 'composition_encounter_id'],
    composition_author_id: ['author_id', 'composition_author_id'],
    composition_date: ['date', 'composition_date'],
    composition_url: ['url', 'composition_url'],
    composition_version: ['version', 'composition_version']
  },
  account: {
    account_id: ['account_identifier', 'accountid', 'account_number'],
    account_status: ['status', 'account_status'],
    account_billing_status: ['billing_status', 'account_billing_status'],
    account_type: ['type', 'account_type'],
    account_name: ['name', 'account_name'],
    account_subject_ids: ['subject_ids', 'subject_id', 'account_subject_ids'],
    account_service_period_start: ['service_period_start', 'account_service_period_start'],
    account_service_period_end: ['service_period_end', 'account_service_period_end'],
    account_coverage_id: ['coverage_id', 'account_coverage_id'],
    account_coverage_priority: ['coverage_priority', 'account_coverage_priority'],
    account_owner_id: ['owner_id', 'account_owner_id'],
    account_description: ['description', 'account_description'],
    account_guarantor_party_id: ['guarantor_party_id', 'account_guarantor_party_id'],
    account_guarantor_on_hold: ['guarantor_on_hold', 'account_guarantor_on_hold'],
    account_guarantor_period_start: ['guarantor_period_start', 'account_guarantor_period_start'],
    account_guarantor_period_end: ['guarantor_period_end', 'account_guarantor_period_end'],
    account_currency: ['currency', 'account_currency'],
    account_balance_amount: ['balance_amount', 'account_balance_amount'],
    account_balance_currency: ['balance_currency', 'account_balance_currency'],
    account_calculated_at: ['calculated_at', 'account_calculated_at'],
    account_related_account_id: ['related_account_id', 'account_related_account_id'],
    account_related_account_relationship: ['related_account_relationship', 'account_related_account_relationship'],
    account_diagnosis_condition_id: ['diagnosis_condition_id', 'account_diagnosis_condition_id'],
    account_diagnosis_sequence: ['diagnosis_sequence', 'account_diagnosis_sequence'],
    account_diagnosis_date: ['diagnosis_date', 'account_diagnosis_date'],
    account_procedure_code: ['procedure_code', 'account_procedure_code'],
    account_procedure_sequence: ['procedure_sequence', 'account_procedure_sequence'],
    account_procedure_date: ['procedure_date', 'account_procedure_date']
  },
  chargeItem: {
    charge_item_id: ['charge_item_identifier', 'chargeitem_id', 'chargeitemid'],
    charge_item_status: ['status', 'charge_item_status'],
    charge_item_code: ['code', 'charge_item_code'],
    charge_item_subject_id: ['subject_id', 'charge_item_subject_id', 'patient_id'],
    charge_item_encounter_id: ['encounter_id', 'charge_item_encounter_id'],
    charge_item_occurrence_date_time: ['occurrence_date_time', 'occurrence_datetime', 'charge_item_occurrence_date_time'],
    charge_item_occurrence_start: ['occurrence_start', 'charge_item_occurrence_start'],
    charge_item_occurrence_end: ['occurrence_end', 'charge_item_occurrence_end'],
    charge_item_quantity_value: ['quantity_value', 'charge_item_quantity_value'],
    charge_item_quantity_unit: ['quantity_unit', 'charge_item_quantity_unit'],
    charge_item_enterer_id: ['enterer_id', 'charge_item_enterer_id'],
    charge_item_entered_date: ['entered_date', 'charge_item_entered_date'],
    charge_item_account_id: ['account_id', 'charge_item_account_id'],
    charge_item_total_price_value: ['total_price_value', 'charge_item_total_price_value'],
    charge_item_total_price_currency: ['total_price_currency', 'charge_item_total_price_currency']
  },
  chargeItemDefinition: {
    charge_item_definition_id: ['charge_item_definition_identifier', 'chargeitemdefinition_id', 'chargeitemdefinitionid'],
    charge_item_definition_url: ['url', 'charge_item_definition_url'],
    charge_item_definition_version: ['version', 'charge_item_definition_version'],
    charge_item_definition_status: ['status', 'charge_item_definition_status'],
    charge_item_definition_code: ['code', 'charge_item_definition_code'],
    charge_item_definition_name: ['name', 'charge_item_definition_name'],
    charge_item_definition_title: ['title', 'charge_item_definition_title'],
    charge_item_definition_publisher: ['publisher', 'charge_item_definition_publisher'],
    charge_item_definition_date: ['date', 'charge_item_definition_date']
  },
  device: {
    device_id: ['device_identifier', 'deviceid', 'device_id'],
    device_status: ['status', 'device_status'],
    device_display_name: ['display_name', 'device_display_name'],
    device_manufacturer: ['manufacturer', 'device_manufacturer'],
    device_model_number: ['model_number', 'device_model_number'],
    device_serial_number: ['serial_number', 'device_serial_number'],
    device_lot_number: ['lot_number', 'device_lot_number'],
    device_subject_id: ['subject_id', 'patient_id', 'device_subject_id'],
    device_owner_id: ['owner_id', 'device_owner_id'],
    device_location_id: ['location_id', 'device_location_id']
  },
  deviceMetric: {
    device_metric_id: ['device_metric_identifier', 'devicemetric_id', 'devicemetricid'],
    device_metric_status: ['status', 'device_metric_status'],
    device_metric_type: ['type', 'device_metric_type'],
    device_metric_unit: ['unit', 'device_metric_unit'],
    device_metric_device_id: ['device_id', 'device_metric_device_id'],
    device_metric_operational_status: ['operational_status', 'device_metric_operational_status'],
    device_metric_color: ['color', 'device_metric_color'],
    device_metric_category: ['category', 'device_metric_category'],
    device_metric_frequency_value: ['frequency_value', 'device_metric_frequency_value'],
    device_metric_frequency_unit: ['frequency_unit', 'device_metric_frequency_unit']
  },
  coverage: {
    coverage_id: ['coverage_identifier', 'coverageid', 'policy_id'],
    coverage_status: ['status', 'coverage_status'],
    coverage_kind: ['kind', 'coverage_kind'],
    coverage_type: ['type', 'coverage_type'],
    coverage_policy_holder_id: ['policy_holder_id', 'coverage_policy_holder_id'],
    coverage_subscriber_id: ['subscriber_id', 'coverage_subscriber_id'],
    coverage_beneficiary_id: ['beneficiary_id', 'coverage_beneficiary_id', 'patient_id'],
    coverage_dependent: ['dependent', 'coverage_dependent'],
    coverage_relationship: ['relationship', 'coverage_relationship'],
    coverage_period_start: ['period_start', 'coverage_period_start', 'coverage_start'],
    coverage_period_end: ['period_end', 'coverage_period_end', 'coverage_end'],
    coverage_insurer_id: ['insurer_id', 'coverage_insurer_id', 'payer_id'],
    coverage_class_type: ['class_type', 'coverage_class_type'],
    coverage_class_value: ['class_value', 'coverage_class_value'],
    coverage_class_name: ['class_name', 'coverage_class_name'],
    coverage_order: ['order', 'coverage_order'],
    coverage_network: ['network', 'coverage_network'],
    coverage_payment_party_id: ['payment_party_id', 'coverage_payment_party_id'],
    coverage_payment_responsibility: ['payment_responsibility', 'coverage_payment_responsibility'],
    coverage_cost_type: ['cost_type', 'coverage_cost_type'],
    coverage_cost_category: ['cost_category', 'coverage_cost_category'],
    coverage_cost_network: ['cost_network', 'coverage_cost_network'],
    coverage_cost_unit: ['cost_unit', 'coverage_cost_unit'],
    coverage_cost_term: ['cost_term', 'coverage_cost_term'],
    coverage_cost_value_quantity: ['cost_value_quantity', 'coverage_cost_value_quantity'],
    coverage_cost_value_unit: ['cost_value_unit', 'coverage_cost_value_unit'],
    coverage_cost_value_money: ['cost_value_money', 'coverage_cost_value_money'],
    coverage_cost_currency: ['cost_currency', 'coverage_cost_currency'],
    coverage_cost_exception_type: ['cost_exception_type', 'coverage_cost_exception_type'],
    coverage_cost_exception_start: ['cost_exception_start', 'coverage_cost_exception_start'],
    coverage_cost_exception_end: ['cost_exception_end', 'coverage_cost_exception_end'],
    coverage_subrogation: ['subrogation', 'coverage_subrogation'],
    coverage_contract_id: ['contract_id', 'coverage_contract_id'],
    coverage_insurance_plan_id: ['insurance_plan_id', 'coverage_insurance_plan_id']
  },
  explanationOfBenefit: {
    explanation_of_benefit_id: ['eob_id', 'explanation_of_benefit_identifier', 'explanationofbenefit_id', 'explanationofbenefitid'],
    explanation_of_benefit_status: ['status', 'eob_status', 'explanation_of_benefit_status'],
    explanation_of_benefit_type: ['type', 'eob_type', 'explanation_of_benefit_type'],
    explanation_of_benefit_sub_type: ['sub_type', 'eob_sub_type', 'explanation_of_benefit_sub_type'],
    explanation_of_benefit_use: ['use', 'eob_use', 'explanation_of_benefit_use'],
    explanation_of_benefit_patient_id: ['patient_id', 'eob_patient_id', 'explanation_of_benefit_patient_id'],
    explanation_of_benefit_billable_start: ['billable_start', 'eob_billable_start', 'explanation_of_benefit_billable_start'],
    explanation_of_benefit_billable_end: ['billable_end', 'eob_billable_end', 'explanation_of_benefit_billable_end'],
    explanation_of_benefit_created: ['created', 'eob_created', 'explanation_of_benefit_created'],
    explanation_of_benefit_enterer_id: ['enterer_id', 'eob_enterer_id'],
    explanation_of_benefit_insurer_id: ['insurer_id', 'eob_insurer_id'],
    explanation_of_benefit_provider_id: ['provider_id', 'eob_provider_id'],
    explanation_of_benefit_priority: ['priority', 'eob_priority'],
    explanation_of_benefit_claim_id: ['claim_id', 'eob_claim_id'],
    explanation_of_benefit_claim_response_id: ['claim_response_id', 'eob_claim_response_id'],
    explanation_of_benefit_outcome: ['outcome', 'eob_outcome'],
    explanation_of_benefit_disposition: ['disposition', 'eob_disposition'],
    explanation_of_benefit_pre_auth_ref: ['pre_auth_ref', 'eob_pre_auth_ref'],
    explanation_of_benefit_total_value: ['total_value', 'eob_total_value'],
    explanation_of_benefit_total_currency: ['total_currency', 'eob_total_currency'],
    explanation_of_benefit_item_sequence: ['item_sequence', 'eob_item_sequence'],
    explanation_of_benefit_item_product_or_service: ['item_product_or_service', 'eob_item_product_or_service'],
    explanation_of_benefit_item_quantity: ['item_quantity', 'eob_item_quantity'],
    explanation_of_benefit_item_unit_price: ['item_unit_price', 'eob_item_unit_price'],
    explanation_of_benefit_item_net: ['item_net', 'eob_item_net']
  },
  schedule: {
    schedule_id: ['sched_id', 'schedule_identifier', 'scheduleid'],
    schedule_active: ['sched_active', 'active'],
    schedule_name: ['sched_name', 'name'],
    schedule_actor_id: ['sched_actor_id', 'actor_id'],
    schedule_start: ['sched_start', 'start'],
    schedule_end: ['sched_end', 'end'],
    schedule_comment: ['sched_comment', 'comment'],
    schedule_service_category: ['sched_service_category', 'service_category'],
    schedule_service_type: ['sched_service_type', 'service_type'],
    schedule_specialty: ['sched_specialty', 'specialty']
  },
  slot: {
    slot_id: ['slot_id', 'slot_identifier'],
    slot_status: ['slot_status', 'status'],
    slot_start: ['slot_start', 'start'],
    slot_end: ['slot_end', 'end'],
    slot_schedule_id: ['slot_schedule_id', 'schedule_id'],
    slot_overbooked: ['slot_overbooked', 'overbooked'],
    slot_comment: ['slot_comment', 'comment'],
    slot_service_category: ['slot_service_category', 'service_category'],
    slot_service_type: ['slot_service_type', 'service_type'],
    slot_specialty: ['slot_specialty', 'specialty'],
    slot_appointment_type: ['slot_appointment_type', 'appointment_type']
  },
  diagnosticReport: {
    diagnostic_report_id: ['diag_report_id', 'diagnosticreport_id'],
    diagnostic_report_status: ['diag_report_status', 'diagnostic_report_status'],
    diagnostic_report_code: ['diag_report_code', 'diagnostic_report_code'],
    diagnostic_report_code_system: ['diag_report_code_system', 'diagnostic_report_code_system'],
    diagnostic_report_display: ['diag_report_display', 'diagnostic_report_display'],
    diagnostic_report_category: ['diag_report_category', 'diagnostic_report_category'],
    diagnostic_report_subject_id: ['diag_report_subject_id', 'subject_id', 'patient_id'],
    diagnostic_report_encounter_id: ['diag_report_encounter_id', 'encounter_id'],
    diagnostic_report_effective_date: ['diag_report_effective_date', 'effective_date'],
    diagnostic_report_effective_start: ['diag_report_effective_start', 'effective_start'],
    diagnostic_report_effective_end: ['diag_report_effective_end', 'effective_end'],
    diagnostic_report_issued: ['diag_report_issued', 'issued'],
    diagnostic_report_performer_id: ['diag_report_performer_id', 'performer_id'],
    diagnostic_report_result_ids: ['diag_report_result_ids', 'result_ids'],
    diagnostic_report_conclusion: ['diag_report_conclusion', 'conclusion'],
    diagnostic_report_note: ['diag_report_note', 'note']
  },
  relatedPerson: {
    related_person_id: ['related_person_id', 'relatedperson_id', 'rp_id'],
    related_person_active: ['related_person_active', 'active'],
    related_person_patient_id: ['related_person_patient_id', 'patient_id'],
    related_person_relationship: ['related_person_relationship', 'relationship'],
    related_person_first_name: ['related_person_first_name', 'first_name'],
    related_person_last_name: ['related_person_last_name', 'last_name'],
    related_person_phone: ['related_person_phone', 'phone'],
    related_person_email: ['related_person_email', 'email'],
    related_person_gender: ['related_person_gender', 'gender'],
    related_person_birth_date: ['related_person_birth_date', 'birth_date'],
    related_person_address_line1: ['related_person_address_line1', 'address_line1'],
    related_person_address_line2: ['related_person_address_line2', 'address_line2'],
    related_person_city: ['related_person_city', 'city'],
    related_person_state: ['related_person_state', 'state'],
    related_person_postal_code: ['related_person_postal_code', 'postal_code'],
    related_person_country: ['related_person_country', 'country']
  },
  location: {
    location_id: ['loc_id', 'location_identifier', 'locationid', 'departmentid', 'dept_id', 'location_id'],
    location_status: ['loc_status', 'status'],
    location_name: ['loc_name', 'name', 'departmentname', 'department_name', 'dept_name', 'location_name'],
    location_alias: ['loc_alias', 'alias'],
    location_description: ['loc_description', 'description'],
    location_mode: ['loc_mode', 'mode'],
    location_type: ['loc_type', 'type'],
    location_address_line1: ['loc_address_line1', 'address_line1'],
    location_address_line2: ['loc_address_line2', 'address_line2'],
    location_city: ['loc_city', 'city'],
    location_state: ['loc_state', 'state'],
    location_postal_code: ['loc_postal_code', 'postal_code'],
    location_country: ['loc_country', 'country'],
    location_managing_org_id: ['loc_managing_org_id', 'managing_organization_id'],
    location_part_of_id: ['loc_part_of_id', 'part_of_id']
  },
  specimen: {
    specimen_id: ['specimen_id', 'specimen_identifier', 'specimenid'],
    specimen_accession_identifier: ['accession_identifier', 'accession_id'],
    specimen_status: ['status'],
    specimen_type: ['type'],
    specimen_subject_id: ['subject_id', 'patient_id'],
    specimen_received_time: ['received_time'],
    specimen_parent_ids: ['parent_ids', 'parent_id'],
    specimen_request_ids: ['request_ids', 'request_id'],
    specimen_combined: ['combined'],
    specimen_role: ['role'],
    specimen_feature_type: ['feature_type'],
    specimen_feature_description: ['feature_description'],
    specimen_collection_collector_id: ['collection_collector_id', 'collector_id'],
    specimen_collection_collected_date: ['collection_collected_date', 'collected_date'],
    specimen_collection_collected_start: ['collection_collected_start', 'collected_start'],
    specimen_collection_collected_end: ['collection_collected_end', 'collected_end'],
    specimen_collection_duration_value: ['collection_duration_value', 'collection_duration'],
    specimen_collection_duration_unit: ['collection_duration_unit'],
    specimen_collection_quantity_value: ['collection_quantity_value', 'collection_quantity'],
    specimen_collection_quantity_unit: ['collection_quantity_unit'],
    specimen_collection_method: ['collection_method'],
    specimen_collection_device_id: ['collection_device_id', 'collection_device'],
    specimen_collection_procedure_id: ['collection_procedure_id', 'collection_procedure'],
    specimen_collection_body_site: ['collection_body_site'],
    specimen_collection_fasting_status: ['collection_fasting_status'],
    specimen_collection_fasting_duration_value: ['collection_fasting_duration_value', 'collection_fasting_duration'],
    specimen_collection_fasting_duration_unit: ['collection_fasting_duration_unit'],
    specimen_processing_description: ['processing_description'],
    specimen_processing_method: ['processing_method'],
    specimen_processing_additive_ids: ['processing_additive_ids', 'processing_additive_id'],
    specimen_processing_time_date: ['processing_time_date'],
    specimen_processing_time_start: ['processing_time_start'],
    specimen_processing_time_end: ['processing_time_end'],
    specimen_container_device_id: ['container_device_id', 'container_device'],
    specimen_container_location_id: ['container_location_id', 'container_location'],
    specimen_container_quantity_value: ['container_quantity_value', 'container_specimen_quantity_value'],
    specimen_container_quantity_unit: ['container_quantity_unit', 'container_specimen_quantity_unit'],
    specimen_condition: ['condition'],
    specimen_note: ['note']
  },
  imagingStudy: {
    imaging_study_id: ['imaging_study_id', 'imagingstudy_id', 'study_id'],
    imaging_study_identifier: ['imaging_study_identifier', 'study_identifier'],
    imaging_study_status: ['status'],
    imaging_study_modality: ['modality'],
    imaging_study_subject_id: ['subject_id', 'patient_id'],
    imaging_study_encounter_id: ['encounter_id'],
    imaging_study_started: ['started', 'study_started'],
    imaging_study_based_on_ids: ['based_on_ids', 'based_on_id'],
    imaging_study_part_of_ids: ['part_of_ids', 'part_of_id'],
    imaging_study_referrer_id: ['referrer_id', 'referrer'],
    imaging_study_endpoint_ids: ['endpoint_ids', 'endpoint_id'],
    imaging_study_number_of_series: ['number_of_series', 'series_count'],
    imaging_study_number_of_instances: ['number_of_instances', 'instance_count'],
    imaging_study_procedure: ['procedure'],
    imaging_study_location_id: ['location_id', 'location'],
    imaging_study_reason: ['reason'],
    imaging_study_note: ['note'],
    imaging_study_description: ['description'],
    imaging_series_uid: ['series_uid'],
    imaging_series_number: ['series_number'],
    imaging_series_modality: ['series_modality'],
    imaging_series_description: ['series_description'],
    imaging_series_number_of_instances: ['series_number_of_instances'],
    imaging_series_endpoint_ids: ['series_endpoint_ids', 'series_endpoint_id'],
    imaging_series_body_site: ['series_body_site'],
    imaging_series_laterality: ['series_laterality'],
    imaging_series_specimen_ids: ['series_specimen_ids', 'series_specimen_id'],
    imaging_series_started: ['series_started'],
    imaging_series_performer_id: ['series_performer_id', 'series_actor_id'],
    imaging_instance_uid: ['instance_uid'],
    imaging_instance_sop_class: ['instance_sop_class'],
    imaging_instance_number: ['instance_number'],
    imaging_instance_title: ['instance_title']
  },
  allergyIntolerance: {
    allergy_id: ['allergy_id', 'allergy_identifier', 'allergyintolerance_id'],
    allergy_clinical_status: ['clinical_status'],
    allergy_verification_status: ['verification_status'],
    allergy_type: ['type'],
    allergy_category: ['category'],
    allergy_criticality: ['criticality'],
    allergy_code: ['code', 'allergy_code'],
    allergy_code_system: ['code_system', 'allergy_code_system'],
    allergy_display: ['display', 'allergy_display'],
    allergy_patient_id: ['patient_id', 'subject_id'],
    allergy_encounter_id: ['encounter_id'],
    allergy_onset_date: ['onset_date', 'onset_datetime'],
    allergy_onset_start: ['onset_start'],
    allergy_onset_end: ['onset_end'],
    allergy_onset_text: ['onset_text'],
    allergy_recorded_date: ['recorded_date'],
    allergy_participant_actor_id: ['participant_actor_id'],
    allergy_participant_function: ['participant_function'],
    allergy_last_occurrence: ['last_occurrence'],
    allergy_note: ['note'],
    allergy_reaction_substance: ['reaction_substance'],
    allergy_reaction_manifestation: ['reaction_manifestation'],
    allergy_reaction_description: ['reaction_description'],
    allergy_reaction_onset: ['reaction_onset'],
    allergy_reaction_severity: ['reaction_severity'],
    allergy_reaction_exposure_route: ['reaction_exposure_route'],
    allergy_reaction_note: ['reaction_note']
  },
  immunization: {
    immunization_id: ['immunization_id', 'immunization_identifier', 'immunizationid'],
    immunization_status: ['status'],
    immunization_status_reason: ['status_reason'],
    immunization_vaccine_code: ['vaccine_code'],
    immunization_vaccine_system: ['vaccine_system'],
    immunization_vaccine_display: ['vaccine_display'],
    immunization_based_on_ids: ['based_on_ids', 'based_on_id'],
    immunization_administered_product_id: ['administered_product_id', 'administered_product'],
    immunization_manufacturer_id: ['manufacturer_id', 'manufacturer'],
    immunization_lot_number: ['lot_number'],
    immunization_expiration_date: ['expiration_date'],
    immunization_patient_id: ['patient_id', 'subject_id'],
    immunization_encounter_id: ['encounter_id'],
    immunization_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id'],
    immunization_occurrence_date: ['occurrence_date', 'occurrence_datetime'],
    immunization_occurrence_string: ['occurrence_string'],
    immunization_primary_source: ['primary_source'],
    immunization_information_source_id: ['information_source_id'],
    immunization_location_id: ['location_id', 'location'],
    immunization_site: ['site'],
    immunization_route: ['route'],
    immunization_dose_value: ['dose_value', 'dose'],
    immunization_dose_unit: ['dose_unit'],
    immunization_performer_actor_id: ['performer_actor_id', 'performer_id'],
    immunization_performer_function: ['performer_function'],
    immunization_note: ['note'],
    immunization_reason: ['reason'],
    immunization_is_subpotent: ['is_subpotent'],
    immunization_subpotent_reason: ['subpotent_reason'],
    immunization_program_eligibility_program: ['program_eligibility_program'],
    immunization_program_eligibility_status: ['program_eligibility_status'],
    immunization_funding_source: ['funding_source'],
    immunization_reaction_date: ['reaction_date'],
    immunization_reaction_manifestation: ['reaction_manifestation'],
    immunization_reaction_reported: ['reaction_reported'],
    immunization_protocol_series: ['protocol_series'],
    immunization_protocol_authority_id: ['protocol_authority_id'],
    immunization_protocol_target_disease: ['protocol_target_disease'],
    immunization_protocol_dose_number: ['protocol_dose_number'],
    immunization_protocol_series_doses: ['protocol_series_doses']
  },
  episodeOfCare: {
    episode_of_care_id: ['episode_id', 'episodeofcare_id', 'eoc_id'],
    episode_status: ['status'],
    episode_type: ['type'],
    episode_patient_id: ['patient_id', 'subject_id'],
    episode_managing_org_id: ['managing_organization_id', 'managing_org_id'],
    episode_period_start: ['period_start', 'start_date', 'start'],
    episode_period_end: ['period_end', 'end_date', 'end'],
    episode_care_manager_id: ['care_manager_id', 'care_manager'],
    episode_care_team_ids: ['care_team_ids', 'care_team_id', 'care_team'],
    episode_account_ids: ['account_ids', 'account_id', 'account'],
    episode_referral_request_ids: ['referral_request_ids', 'referral_request_id', 'referral_request'],
    episode_reason: ['reason'],
    episode_diagnosis: ['diagnosis'],
    episode_status_history_status: ['status_history_status'],
    episode_status_history_start: ['status_history_start'],
    episode_status_history_end: ['status_history_end']
  },
  carePlan: {
    care_plan_id: ['careplan_id', 'care_plan_identifier', 'careplan_identifier'],
    care_plan_status: ['status'],
    care_plan_intent: ['intent'],
    care_plan_category: ['category'],
    care_plan_title: ['title'],
    care_plan_description: ['description'],
    care_plan_subject_id: ['patient_id', 'subject_id'],
    care_plan_encounter_id: ['encounter_id'],
    care_plan_period_start: ['period_start', 'start_date', 'start'],
    care_plan_period_end: ['period_end', 'end_date', 'end'],
    care_plan_created: ['created', 'created_date'],
    care_plan_custodian_id: ['custodian_id', 'custodian'],
    care_plan_contributor_ids: ['contributor_ids', 'contributors'],
    care_plan_care_team_ids: ['care_team_ids', 'care_team_id', 'care_team'],
    care_plan_addresses: ['addresses', 'addressed'],
    care_plan_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id', 'supporting_info'],
    care_plan_goal_ids: ['goal_ids', 'goal_id', 'goals'],
    care_plan_activity_reference: ['activity_reference', 'planned_activity_reference'],
    care_plan_activity_progress: ['activity_progress'],
    care_plan_activity_performed: ['activity_performed', 'performed_activity'],
    care_plan_note: ['note'],
    care_plan_instantiates_canonical: ['instantiates_canonical'],
    care_plan_instantiates_uri: ['instantiates_uri'],
    care_plan_based_on_ids: ['based_on_ids', 'based_on_id'],
    care_plan_replaces_ids: ['replaces_ids', 'replaces_id'],
    care_plan_part_of_ids: ['part_of_ids', 'part_of_id']
  },
  careTeam: {
    care_team_id: ['careteam_id', 'care_team_identifier', 'careteam_identifier'],
    care_team_status: ['status'],
    care_team_category: ['category'],
    care_team_name: ['name', 'team_name'],
    care_team_subject_id: ['patient_id', 'subject_id'],
    care_team_period_start: ['period_start', 'start_date', 'start'],
    care_team_period_end: ['period_end', 'end_date', 'end'],
    care_team_participant_role: ['participant_role', 'role'],
    care_team_participant_member_id: ['participant_member_id', 'member_id', 'participant_member'],
    care_team_participant_on_behalf_of_id: ['participant_on_behalf_of_id', 'on_behalf_of_id'],
    care_team_participant_coverage_start: ['participant_coverage_start'],
    care_team_participant_coverage_end: ['participant_coverage_end'],
    care_team_reason: ['reason'],
    care_team_managing_org_ids: ['managing_org_ids', 'managing_org_id'],
    care_team_phone: ['phone'],
    care_team_email: ['email'],
    care_team_note: ['note']
  },
  goal: {
    goal_id: ['goal_identifier', 'goalid'],
    goal_lifecycle_status: ['lifecycle_status', 'status'],
    goal_achievement_status: ['achievement_status'],
    goal_category: ['category'],
    goal_continuous: ['continuous'],
    goal_priority: ['priority'],
    goal_description: ['description', 'goal_description'],
    goal_subject_id: ['subject_id', 'patient_id'],
    goal_start_date: ['start_date'],
    goal_start_code: ['start_code', 'start_codeable_concept'],
    goal_target_measure: ['target_measure'],
    goal_target_detail: ['target_detail', 'detail'],
    goal_target_due_date: ['target_due_date', 'due_date'],
    goal_status_date: ['status_date'],
    goal_status_reason: ['status_reason'],
    goal_source_id: ['source_id'],
    goal_addresses: ['addresses', 'addressed'],
    goal_note: ['note'],
    goal_outcome: ['outcome']
  },
  serviceRequest: {
    service_request_id: ['servicerequest_id', 'service_request_identifier', 'service_requestid'],
    service_request_status: ['status'],
    service_request_intent: ['intent'],
    service_request_category: ['category'],
    service_request_priority: ['priority'],
    service_request_do_not_perform: ['do_not_perform'],
    service_request_code: ['code'],
    service_request_code_system: ['code_system'],
    service_request_code_display: ['code_display'],
    service_request_subject_id: ['subject_id', 'patient_id'],
    service_request_encounter_id: ['encounter_id'],
    service_request_occurrence_date: ['occurrence_date', 'occurrence_datetime'],
    service_request_occurrence_start: ['occurrence_start'],
    service_request_occurrence_end: ['occurrence_end'],
    service_request_as_needed: ['as_needed'],
    service_request_authored_on: ['authored_on'],
    service_request_requester_id: ['requester_id'],
    service_request_performer_type: ['performer_type'],
    service_request_performer_ids: ['performer_ids', 'performer_id'],
    service_request_location_ids: ['location_ids', 'location_id'],
    service_request_reason: ['reason'],
    service_request_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id'],
    service_request_specimen_ids: ['specimen_ids', 'specimen_id'],
    service_request_body_site: ['body_site'],
    service_request_note: ['note'],
    service_request_patient_instruction: ['patient_instruction'],
    service_request_instantiates_canonical: ['instantiates_canonical'],
    service_request_instantiates_uri: ['instantiates_uri'],
    service_request_based_on_ids: ['based_on_ids', 'based_on_id'],
    service_request_replaces_ids: ['replaces_ids', 'replaces_id'],
    service_request_requisition: ['requisition']
  },
  task: {
    task_id: ['task_identifier', 'taskid', 'task_id'],
    task_status: ['status'],
    task_intent: ['intent'],
    task_priority: ['priority'],
    task_do_not_perform: ['do_not_perform'],
    task_code: ['code'],
    task_code_system: ['code_system'],
    task_code_display: ['code_display'],
    task_description: ['description'],
    task_focus_id: ['focus_id'],
    task_for_id: ['for_id', 'beneficiary_id'],
    task_encounter_id: ['encounter_id'],
    task_requested_start: ['requested_start'],
    task_requested_end: ['requested_end'],
    task_execution_start: ['execution_start'],
    task_execution_end: ['execution_end'],
    task_authored_on: ['authored_on'],
    task_last_modified: ['last_modified'],
    task_requester_id: ['requester_id'],
    task_requested_performer_ids: ['requested_performer_ids', 'requested_performer_id'],
    task_owner_id: ['owner_id'],
    task_performer_id: ['performer_id'],
    task_performer_function: ['performer_function'],
    task_location: ['location'],
    task_reason: ['reason'],
    task_insurance_ids: ['insurance_ids', 'insurance_id'],
    task_note: ['note'],
    task_relevant_history_ids: ['relevant_history_ids', 'relevant_history_id'],
    task_instantiates_canonical: ['instantiates_canonical'],
    task_instantiates_uri: ['instantiates_uri'],
    task_based_on_ids: ['based_on_ids', 'based_on_id'],
    task_part_of_ids: ['part_of_ids', 'part_of_id'],
    task_group_identifier: ['group_identifier'],
    task_status_reason: ['status_reason'],
    task_business_status: ['business_status']
  },
  communication: {
    communication_id: ['communication_identifier', 'communicationid', 'communication_id'],
    communication_status: ['status'],
    communication_status_reason: ['status_reason'],
    communication_category: ['category'],
    communication_priority: ['priority'],
    communication_medium: ['medium'],
    communication_subject_id: ['subject_id', 'patient_id'],
    communication_topic: ['topic'],
    communication_about_ids: ['about_ids', 'about_id'],
    communication_encounter_id: ['encounter_id'],
    communication_sent: ['sent'],
    communication_received: ['received'],
    communication_recipient_ids: ['recipient_ids', 'recipient_id'],
    communication_sender_id: ['sender_id'],
    communication_reason: ['reason'],
    communication_payload: ['payload'],
    communication_note: ['note'],
    communication_instantiates_canonical: ['instantiates_canonical'],
    communication_instantiates_uri: ['instantiates_uri'],
    communication_based_on_ids: ['based_on_ids', 'based_on_id'],
    communication_part_of_ids: ['part_of_ids', 'part_of_id'],
    communication_in_response_to_ids: ['in_response_to_ids', 'in_response_to_id']
  },
  communicationRequest: {
    communication_request_id: ['communication_request_identifier', 'communicationrequest_id', 'communication_requestid'],
    communication_request_status: ['status'],
    communication_request_status_reason: ['status_reason'],
    communication_request_intent: ['intent'],
    communication_request_category: ['category'],
    communication_request_priority: ['priority'],
    communication_request_do_not_perform: ['do_not_perform'],
    communication_request_medium: ['medium'],
    communication_request_subject_id: ['subject_id', 'patient_id'],
    communication_request_about_ids: ['about_ids', 'about_id'],
    communication_request_encounter_id: ['encounter_id'],
    communication_request_payload: ['payload'],
    communication_request_occurrence_date: ['occurrence_date', 'occurrence_datetime'],
    communication_request_occurrence_start: ['occurrence_start'],
    communication_request_occurrence_end: ['occurrence_end'],
    communication_request_authored_on: ['authored_on'],
    communication_request_requester_id: ['requester_id'],
    communication_request_recipient_ids: ['recipient_ids', 'recipient_id'],
    communication_request_information_provider_ids: ['information_provider_ids', 'information_provider_id'],
    communication_request_reason: ['reason'],
    communication_request_note: ['note'],
    communication_request_based_on_ids: ['based_on_ids', 'based_on_id'],
    communication_request_replaces_ids: ['replaces_ids', 'replaces_id'],
    communication_request_group_identifier: ['group_identifier']
  },
  questionnaire: {
    questionnaire_id: ['questionnaire_identifier', 'questionnaireid', 'questionnaire_id'],
    questionnaire_url: ['url'],
    questionnaire_version: ['version'],
    questionnaire_name: ['name'],
    questionnaire_title: ['title'],
    questionnaire_status: ['status'],
    questionnaire_date: ['date'],
    questionnaire_publisher: ['publisher'],
    questionnaire_description: ['description'],
    questionnaire_subject_type: ['subject_type'],
    questionnaire_item_link_id: ['item_link_id', 'link_id'],
    questionnaire_item_text: ['item_text', 'question_text'],
    questionnaire_item_type: ['item_type', 'question_type']
  },
  questionnaireResponse: {
    questionnaire_response_id: ['questionnaire_response_identifier', 'questionnaireresponse_id', 'questionnaire_responseid'],
    questionnaire_response_questionnaire: ['questionnaire'],
    questionnaire_response_status: ['status'],
    questionnaire_response_subject_id: ['subject_id', 'patient_id'],
    questionnaire_response_encounter_id: ['encounter_id'],
    questionnaire_response_authored: ['authored'],
    questionnaire_response_author_id: ['author_id'],
    questionnaire_response_source_id: ['source_id'],
    questionnaire_response_item_link_id: ['item_link_id', 'link_id'],
    questionnaire_response_item_text: ['item_text', 'question_text'],
    questionnaire_response_item_answer: ['item_answer', 'answer'],
    questionnaire_response_based_on_ids: ['based_on_ids', 'based_on_id'],
    questionnaire_response_part_of_ids: ['part_of_ids', 'part_of_id']
  },
  codeSystem: {
    code_system_id: ['code_system_identifier', 'codesystem_id', 'codesystem_identifier'],
    code_system_url: ['url'],
    code_system_version: ['version'],
    code_system_name: ['name'],
    code_system_title: ['title'],
    code_system_status: ['status'],
    code_system_date: ['date'],
    code_system_publisher: ['publisher'],
    code_system_description: ['description'],
    code_system_content: ['content'],
    code_system_case_sensitive: ['case_sensitive'],
    code_system_concept_code: ['concept_code'],
    code_system_concept_display: ['concept_display'],
    code_system_concept_definition: ['concept_definition']
  },
  valueSet: {
    value_set_id: ['value_set_identifier', 'valueset_id', 'valueset_identifier'],
    value_set_url: ['url'],
    value_set_version: ['version'],
    value_set_name: ['name'],
    value_set_title: ['title'],
    value_set_status: ['status'],
    value_set_date: ['date'],
    value_set_publisher: ['publisher'],
    value_set_description: ['description'],
    value_set_include_system: ['include_system', 'compose_include_system'],
    value_set_include_code: ['include_code', 'compose_include_code'],
    value_set_include_display: ['include_display', 'compose_include_display'],
    value_set_expansion_system: ['expansion_system'],
    value_set_expansion_code: ['expansion_code'],
    value_set_expansion_display: ['expansion_display']
  },
  conceptMap: {
    concept_map_id: ['concept_map_identifier', 'conceptmap_id', 'conceptmap_identifier'],
    concept_map_url: ['url'],
    concept_map_version: ['version'],
    concept_map_name: ['name'],
    concept_map_title: ['title'],
    concept_map_status: ['status'],
    concept_map_date: ['date'],
    concept_map_publisher: ['publisher'],
    concept_map_description: ['description'],
    concept_map_source_scope: ['source_scope'],
    concept_map_target_scope: ['target_scope'],
    concept_map_group_source: ['group_source'],
    concept_map_group_target: ['group_target'],
    concept_map_element_code: ['element_code'],
    concept_map_element_display: ['element_display'],
    concept_map_target_code: ['target_code'],
    concept_map_target_display: ['target_display'],
    concept_map_target_relationship: ['target_relationship']
  },
  namingSystem: {
    naming_system_id: ['naming_system_identifier', 'namingsystem_id', 'namingsystem_identifier'],
    naming_system_url: ['url'],
    naming_system_version: ['version'],
    naming_system_name: ['name'],
    naming_system_title: ['title'],
    naming_system_status: ['status'],
    naming_system_kind: ['kind'],
    naming_system_date: ['date'],
    naming_system_publisher: ['publisher'],
    naming_system_responsible: ['responsible'],
    naming_system_description: ['description'],
    naming_system_usage: ['usage'],
    naming_system_unique_id_type: ['unique_id_type'],
    naming_system_unique_id_value: ['unique_id_value'],
    naming_system_unique_id_preferred: ['unique_id_preferred']
  },
  terminologyCapabilities: {
    terminology_capabilities_id: ['terminology_capabilities_identifier', 'terminologycapabilities_id', 'terminologycapabilities_identifier'],
    terminology_capabilities_url: ['url'],
    terminology_capabilities_version: ['version'],
    terminology_capabilities_name: ['name'],
    terminology_capabilities_title: ['title'],
    terminology_capabilities_status: ['status'],
    terminology_capabilities_date: ['date'],
    terminology_capabilities_publisher: ['publisher'],
    terminology_capabilities_description: ['description'],
    terminology_capabilities_kind: ['kind'],
    terminology_capabilities_code_search: ['code_search', 'code_search_mode']
  },
  provenance: {
    provenance_id: ['provenance_identifier', 'provenanceid'],
    provenance_target_ids: ['target_ids', 'targets'],
    provenance_recorded: ['recorded'],
    provenance_activity: ['activity'],
    provenance_agent_who: ['agent_who', 'agent_id'],
    provenance_agent_role: ['agent_role']
  },
  auditEvent: {
    audit_event_id: ['audit_event_identifier', 'auditevent_id', 'auditevent_identifier'],
    audit_event_category: ['category'],
    audit_event_code: ['code'],
    audit_event_action: ['action'],
    audit_event_severity: ['severity'],
    audit_event_recorded: ['recorded'],
    audit_event_agent_who: ['agent_who', 'agent_id'],
    audit_event_agent_role: ['agent_role'],
    audit_event_agent_requestor: ['agent_requestor']
  },
  consent: {
    consent_id: ['consent_identifier', 'consentid'],
    consent_status: ['status'],
    consent_category: ['category'],
    consent_subject_id: ['subject_id', 'patient_id'],
    consent_date: ['date'],
    consent_decision: ['decision'],
    consent_grantor_ids: ['grantor_ids', 'grantor_id'],
    consent_grantee_ids: ['grantee_ids', 'grantee_id']
  },
  documentReference: {
    document_id: ['doc_id', 'document_identifier', 'documentid'],
    document_title: ['doc_title'],
    document_description: ['doc_description'],
    document_format: ['doc_format'],
    document_url: ['doc_url'],
    document_data: ['doc_data'],
    document_content_type: ['doc_content_type', 'mime_type'],
    document_status: ['doc_status']
  },
  binary: {
    binary_id: ['binary_identifier', 'binaryid'],
    binary_content_type: ['content_type', 'mime_type', 'binary_content_type'],
    binary_security_context: ['security_context', 'binary_security_context'],
    binary_data: ['data', 'binary_data']
  },
  practitioner: {
    practitioner_id: ['provider_id', 'providerid', 'clinician_id', 'practitioner_identifier', 'practitionerid'],
    practitioner_first_name: ['practitioner_given', 'practitioner_given_name', 'provider_first_name', 'clinician_first_name'],
    practitioner_middle_name: ['practitioner_middlename', 'provider_middle_name', 'clinician_middle_name'],
    practitioner_last_name: ['practitioner_family', 'practitioner_family_name', 'provider_last_name', 'clinician_last_name'],
    practitioner_name: ['practitioner_full_name', 'provider_name', 'providername', 'clinician_name', 'attend_prsnl_name', 'attending_provider_name'],
    practitioner_gender: ['practitioner_sex', 'provider_gender', 'clinician_gender'],
    practitioner_birth_date: ['practitioner_dob', 'provider_dob', 'clinician_dob'],
    practitioner_phone: ['practitioner_phone_number', 'provider_phone', 'clinician_phone', 'practitioner_mobile', 'practitioner_home_phone'],
    practitioner_email: ['practitioner_email_address', 'provider_email', 'clinician_email'],
    practitioner_address_line1: ['practitioner_address', 'practitioner_address1', 'provider_address1', 'practitioner_address_1'],
    practitioner_address_line2: ['practitioner_address2', 'provider_address2', 'practitioner_address_2'],
    practitioner_city: ['practitioner_city', 'provider_city'],
    practitioner_state: ['practitioner_state', 'provider_state', 'practitioner_province'],
    practitioner_postal_code: ['practitioner_zip', 'provider_zip', 'practitioner_postal'],
    practitioner_country: ['practitioner_country', 'provider_country'],
    practitioner_qualification_code: ['practitioner_qualification', 'provider_qualification_code'],
    practitioner_qualification_system: ['practitioner_qualification_system', 'provider_qualification_system'],
    practitioner_qualification_display: ['practitioner_qualification_display', 'provider_qualification_display'],
    practitioner_active: ['provider_active', 'clinician_active']
  },
  practitionerRole: {
    practitioner_role_id: ['role_id', 'practitionerrole_id', 'practitioner_role_identifier'],
    practitioner_role_practitioner_id: ['role_practitioner_id', 'role_provider_id'],
    practitioner_role_organization_id: ['role_organization_id'],
    practitioner_role_code: ['role_code', 'practitionerrole_code'],
    practitioner_role_code_system: ['role_code_system'],
    practitioner_role_code_display: ['role_code_display'],
    practitioner_role_specialty: ['role_specialty', 'specialty_code'],
    practitioner_role_specialty_system: ['specialty_system'],
    practitioner_role_specialty_display: ['specialty_display'],
    practitioner_role_period_start: ['role_period_start', 'role_start'],
    practitioner_role_period_end: ['role_period_end', 'role_end'],
    practitioner_role_active: ['role_active']
  },
  organization: {
    organization_id: ['org_id', 'organization_identifier', 'organizationid'],
    organization_name: ['org_name', 'facility_name'],
    organization_alias: ['org_alias', 'organization_aliases'],
    organization_type_code: ['org_type_code', 'organization_type'],
    organization_type_system: ['org_type_system'],
    organization_type_display: ['org_type_display'],
    organization_phone: ['org_phone', 'organization_phone_number'],
    organization_email: ['org_email', 'organization_email_address'],
    organization_address_line1: ['org_address', 'org_address1', 'organization_address1', 'organization_address_1'],
    organization_address_line2: ['org_address2', 'organization_address2', 'organization_address_2'],
    organization_city: ['org_city', 'organization_city'],
    organization_state: ['org_state', 'organization_state', 'organization_province'],
    organization_postal_code: ['org_zip', 'organization_zip', 'organization_postal'],
    organization_country: ['org_country', 'organization_country'],
    organization_part_of: ['org_parent_id', 'parent_organization_id', 'organization_parent_id'],
    organization_active: ['org_active']
  }
};

export const HEADER_ALIASES: HeaderAliasMap = Object.values(HEADER_ALIAS_SECTIONS)
  .reduce((acc, section) => ({ ...acc, ...section }), {} as HeaderAliasMap);
