export type HeaderAliasMap = Record<string, string[]>;
export type HeaderAliasSections = Record<string, HeaderAliasMap>;

export const HEADER_ALIAS_SECTIONS: HeaderAliasSections = {
  patient: {
    patient_id: ['patient_identifier', 'patient_mrn', 'mrn', 'medical_record_number', 'patientid'],
    patient_first_name: ['first_name', 'fname', 'given_name', 'given', 'patient_given', 'patient_given_name'],
    patient_middle_name: ['middle_name', 'middlename'],
    patient_last_name: ['last_name', 'lname', 'family_name', 'surname', 'patient_family', 'patient_family_name'],
    patient_name: ['name', 'patientname', 'full_name', 'patient_full_name', 'pt_name'],
    patient_gender: ['gender', 'sex', 'gndr'],
    patient_birth_date: ['dob', 'date_of_birth', 'birth_date', 'birthdate'],
    patient_phone: ['phone', 'phone_number', 'mobile', 'cell', 'cell_phone', 'patient_phone_number', 'patient_mobile', 'patient_home_phone'],
    patient_email: ['email', 'email_address'],
    patient_address_line1: ['address', 'address1', 'address_line1', 'street', 'street_address', 'patient_address1', 'patient_address_1'],
    patient_address_line2: ['address2', 'address_line2', 'street2', 'street_address_2', 'patient_address2', 'patient_address_2'],
    patient_city: ['city', 'town'],
    patient_state: ['state', 'province', 'region', 'patient_province'],
    patient_postal_code: ['zip', 'zipcode', 'postal', 'postal_code', 'patient_zip'],
    patient_country: ['country']
  },
  encounter: {
    encounter_id: ['visit_id', 'encounter_identifier', 'encounterid', 'visitid'],
    encounter_class: ['encounter_type', 'visit_class', 'encounterclass'],
    encounter_start: ['encounter_start_time', 'visit_start', 'visit_start_time', 'admit_time', 'admit_datetime'],
    encounter_location: ['visit_location', 'encounter_room'],
    encounter_status: ['encounterstate'],
    encounter_practitioner_id: ['encounter_participant_id', 'encounter_practitioner_ids'],
    encounter_service_provider_id: ['service_provider_id', 'service_provider_organization_id']
  },
  observation: {
    observation_id: ['obs_id', 'observation_identifier', 'observationid'],
    observation_code: ['obs_code', 'test_code', 'loinc_code', 'observationcode'],
    observation_code_system: ['obs_code_system', 'loinc_system'],
    observation_display: ['obs_display', 'test_name', 'observation_name', 'observation_display_name'],
    observation_value: ['obs_value', 'result_value'],
    observation_unit: ['obs_unit', 'result_unit'],
    observation_date: ['obs_date', 'observation_datetime', 'observation_time', 'recorded_datetime'],
    observation_status: ['obs_status', 'result_status']
  },
  medication: {
    medication_id: ['med_id', 'medication_identifier', 'medicationid'],
    medication_code: ['med_code', 'rxnorm_code', 'ndc_code', 'medicationcode'],
    medication_code_system: ['med_code_system', 'rxnorm_system', 'ndc_system'],
    medication_display: ['med_display', 'medication_name', 'drug_name']
  },
  medicationRequest: {
    medication_request_id: ['med_request_id', 'prescription_id', 'order_id'],
    medication_status: ['med_status', 'medication_request_status'],
    medication_authored_on: ['med_authored_on', 'order_date'],
    medication_dose: ['med_dose'],
    medication_dose_unit: ['med_dose_unit', 'dose_unit'],
    medication_route: ['med_route'],
    medication_route_display: ['med_route_display', 'route_display'],
    medication_sig: ['med_sig', 'sig', 'instructions']
  },
  medicationStatement: {
    medication_statement_id: ['med_statement_id', 'medicationstatement_id'],
    medication_statement_status: ['med_statement_status', 'medication_statement_state'],
    medication_statement_category: ['med_statement_category', 'medication_statement_type'],
    medication_statement_medication_code: ['med_statement_code', 'medication_code'],
    medication_statement_medication_code_system: ['med_statement_code_system', 'medication_code_system'],
    medication_statement_medication_display: ['med_statement_display', 'medication_display'],
    medication_statement_subject_id: ['med_statement_subject_id', 'subject_id', 'patient_id'],
    medication_statement_encounter_id: ['med_statement_encounter_id', 'encounter_id'],
    medication_statement_effective_date: ['med_statement_effective_date', 'effective_date'],
    medication_statement_effective_start: ['med_statement_effective_start', 'effective_start'],
    medication_statement_effective_end: ['med_statement_effective_end', 'effective_end'],
    medication_statement_date_asserted: ['med_statement_date_asserted', 'date_asserted'],
    medication_statement_author: ['med_statement_author', 'author_id'],
    medication_statement_information_source: ['med_statement_information_source', 'information_source'],
    medication_statement_reason: ['med_statement_reason', 'reason'],
    medication_statement_note: ['med_statement_note', 'note'],
    medication_statement_dose: ['med_statement_dose', 'dose'],
    medication_statement_dose_unit: ['med_statement_dose_unit', 'dose_unit'],
    medication_statement_route: ['med_statement_route', 'route'],
    medication_statement_route_display: ['med_statement_route_display', 'route_display']
  },
  medicationAdministration: {
    medication_administration_id: ['med_admin_id', 'medicationadministration_id'],
    medication_administration_status: ['med_admin_status', 'status'],
    medication_administration_status_reason: ['med_admin_status_reason', 'status_reason'],
    medication_administration_category: ['med_admin_category', 'category'],
    medication_administration_medication_code: ['med_admin_code', 'medication_code'],
    medication_administration_medication_code_system: ['med_admin_code_system', 'medication_code_system'],
    medication_administration_medication_display: ['med_admin_display', 'medication_display'],
    medication_administration_subject_id: ['med_admin_subject_id', 'subject_id', 'patient_id'],
    medication_administration_encounter_id: ['med_admin_encounter_id', 'encounter_id'],
    medication_administration_occurrence_date: ['med_admin_occurrence_date', 'occurrence_date'],
    medication_administration_occurrence_start: ['med_admin_occurrence_start', 'occurrence_start'],
    medication_administration_occurrence_end: ['med_admin_occurrence_end', 'occurrence_end'],
    medication_administration_recorded: ['med_admin_recorded', 'recorded'],
    medication_administration_is_sub_potent: ['med_admin_is_sub_potent', 'is_sub_potent'],
    medication_administration_sub_potent_reason: ['med_admin_sub_potent_reason', 'sub_potent_reason'],
    medication_administration_performer_actor_id: ['med_admin_performer_actor_id', 'performer_actor_id'],
    medication_administration_performer_function: ['med_admin_performer_function', 'performer_function'],
    medication_administration_reason: ['med_admin_reason', 'reason'],
    medication_administration_request_id: ['med_admin_request_id', 'request_id'],
    medication_administration_device_ids: ['med_admin_device_ids', 'device_ids', 'device_id'],
    medication_administration_note: ['med_admin_note', 'note'],
    medication_administration_based_on_ids: ['med_admin_based_on_ids', 'based_on_ids', 'based_on_id'],
    medication_administration_part_of_ids: ['med_admin_part_of_ids', 'part_of_ids', 'part_of_id'],
    medication_administration_supporting_info_ids: ['med_admin_supporting_info_ids', 'supporting_info_ids', 'supporting_info_id'],
    medication_administration_dose_value: ['med_admin_dose_value', 'dose_value', 'dose'],
    medication_administration_dose_unit: ['med_admin_dose_unit', 'dose_unit'],
    medication_administration_route: ['med_admin_route', 'route'],
    medication_administration_site: ['med_admin_site', 'site'],
    medication_administration_method: ['med_admin_method', 'method'],
    medication_administration_rate_value: ['med_admin_rate_value', 'rate_value'],
    medication_administration_rate_unit: ['med_admin_rate_unit', 'rate_unit']
  },
  capabilityStatement: {
    capability_statement_id: ['capability_statement_id', 'capabilitystatement_id'],
    capability_statement_url: ['capability_url', 'url'],
    capability_statement_identifier: ['identifier'],
    capability_statement_version: ['version'],
    capability_statement_name: ['name'],
    capability_statement_title: ['title'],
    capability_statement_status: ['status'],
    capability_statement_date: ['date'],
    capability_statement_publisher: ['publisher'],
    capability_statement_kind: ['kind'],
    capability_statement_fhir_version: ['fhir_version', 'fhirversion'],
    capability_statement_format: ['format'],
    capability_statement_description: ['description'],
    capability_statement_implementation_url: ['implementation_url'],
    capability_statement_implementation_description: ['implementation_description'],
    capability_statement_software_name: ['software_name'],
    capability_statement_software_version: ['software_version'],
    capability_statement_software_release_date: ['software_release_date'],
    capability_statement_rest_mode: ['rest_mode'],
    capability_statement_rest_documentation: ['rest_documentation']
  },
  operationOutcome: {
    operation_outcome_id: ['operation_outcome_id', 'operationoutcome_id'],
    operation_outcome_severity: ['severity'],
    operation_outcome_code: ['code'],
    operation_outcome_details_system: ['details_system'],
    operation_outcome_details_code: ['details_code'],
    operation_outcome_details_display: ['details_display'],
    operation_outcome_diagnostics: ['diagnostics'],
    operation_outcome_location: ['location'],
    operation_outcome_expression: ['expression']
  },
  parameters: {
    parameter_name: ['name', 'param_name'],
    parameter_value: ['value', 'param_value'],
    parameter_value_string: ['value_string'],
    parameter_value_code: ['value_code'],
    parameter_value_boolean: ['value_boolean', 'value_bool'],
    parameter_value_date: ['value_date'],
    parameter_value_datetime: ['value_datetime', 'value_date_time'],
    parameter_value_integer: ['value_integer', 'value_int'],
    parameter_value_decimal: ['value_decimal'],
    parameter_value_uri: ['value_uri'],
    parameter_value_reference: ['value_reference']
  },
  procedure: {
    procedure_id: ['proc_id', 'procedure_identifier', 'procedureid'],
    procedure_status: ['proc_status', 'procedure_status'],
    procedure_category: ['proc_category', 'procedure_category'],
    procedure_code: ['proc_code', 'procedure_code'],
    procedure_code_system: ['proc_code_system', 'procedure_code_system'],
    procedure_display: ['proc_display', 'procedure_display', 'procedure_name'],
    procedure_subject_id: ['proc_subject_id', 'subject_id', 'patient_id'],
    procedure_encounter_id: ['proc_encounter_id', 'encounter_id'],
    procedure_occurrence_date: ['proc_occurrence_date', 'occurrence_date'],
    procedure_occurrence_start: ['proc_occurrence_start', 'occurrence_start'],
    procedure_occurrence_end: ['proc_occurrence_end', 'occurrence_end'],
    procedure_recorded: ['proc_recorded', 'recorded'],
    procedure_performer_id: ['proc_performer_id', 'performer_id'],
    procedure_location: ['proc_location', 'location'],
    procedure_reason: ['proc_reason', 'reason'],
    procedure_body_site: ['proc_body_site', 'body_site'],
    procedure_note: ['proc_note', 'note']
  },
  condition: {
    condition_id: ['cond_id', 'condition_identifier', 'conditionid'],
    condition_clinical_status: ['cond_clinical_status', 'clinical_status'],
    condition_verification_status: ['cond_verification_status', 'verification_status'],
    condition_category: ['cond_category', 'condition_category'],
    condition_severity: ['cond_severity', 'severity'],
    condition_code: ['cond_code', 'condition_code'],
    condition_code_system: ['cond_code_system', 'condition_code_system'],
    condition_display: ['cond_display', 'condition_display', 'condition_name'],
    condition_body_site: ['cond_body_site', 'body_site'],
    condition_subject_id: ['cond_subject_id', 'subject_id', 'patient_id'],
    condition_encounter_id: ['cond_encounter_id', 'encounter_id'],
    condition_onset_date: ['cond_onset_date', 'onset_date'],
    condition_onset_start: ['cond_onset_start', 'onset_start'],
    condition_onset_end: ['cond_onset_end', 'onset_end'],
    condition_onset_text: ['cond_onset_text', 'onset_text'],
    condition_abatement_date: ['cond_abatement_date', 'abatement_date'],
    condition_abatement_start: ['cond_abatement_start', 'abatement_start'],
    condition_abatement_end: ['cond_abatement_end', 'abatement_end'],
    condition_abatement_text: ['cond_abatement_text', 'abatement_text'],
    condition_recorded_date: ['cond_recorded_date', 'recorded_date'],
    condition_note: ['cond_note', 'note']
  },
  appointment: {
    appointment_id: ['appt_id', 'appointment_identifier', 'appointmentid'],
    appointment_status: ['appt_status', 'status'],
    appointment_description: ['appt_description', 'description'],
    appointment_start: ['appt_start', 'start'],
    appointment_end: ['appt_end', 'end'],
    appointment_minutes_duration: ['appt_minutes_duration', 'minutes_duration', 'duration_minutes'],
    appointment_created: ['appt_created', 'created'],
    appointment_cancellation_date: ['appt_cancellation_date', 'cancellation_date'],
    appointment_subject_id: ['appt_subject_id', 'subject_id', 'patient_id'],
    appointment_participant_id: ['appt_participant_id', 'participant_id'],
    appointment_participant_status: ['appt_participant_status', 'participant_status'],
    appointment_note: ['appt_note', 'note']
  },
  schedule: {
    schedule_id: ['sched_id', 'schedule_identifier', 'scheduleid'],
    schedule_active: ['sched_active', 'active'],
    schedule_name: ['sched_name', 'name'],
    schedule_actor_id: ['sched_actor_id', 'actor_id'],
    schedule_start: ['sched_start', 'start'],
    schedule_end: ['sched_end', 'end'],
    schedule_comment: ['sched_comment', 'comment'],
    schedule_service_category: ['sched_service_category', 'service_category'],
    schedule_service_type: ['sched_service_type', 'service_type'],
    schedule_specialty: ['sched_specialty', 'specialty']
  },
  slot: {
    slot_id: ['slot_id', 'slot_identifier'],
    slot_status: ['slot_status', 'status'],
    slot_start: ['slot_start', 'start'],
    slot_end: ['slot_end', 'end'],
    slot_schedule_id: ['slot_schedule_id', 'schedule_id'],
    slot_overbooked: ['slot_overbooked', 'overbooked'],
    slot_comment: ['slot_comment', 'comment'],
    slot_service_category: ['slot_service_category', 'service_category'],
    slot_service_type: ['slot_service_type', 'service_type'],
    slot_specialty: ['slot_specialty', 'specialty'],
    slot_appointment_type: ['slot_appointment_type', 'appointment_type']
  },
  diagnosticReport: {
    diagnostic_report_id: ['diag_report_id', 'diagnosticreport_id'],
    diagnostic_report_status: ['diag_report_status', 'diagnostic_report_status'],
    diagnostic_report_code: ['diag_report_code', 'diagnostic_report_code'],
    diagnostic_report_code_system: ['diag_report_code_system', 'diagnostic_report_code_system'],
    diagnostic_report_display: ['diag_report_display', 'diagnostic_report_display'],
    diagnostic_report_category: ['diag_report_category', 'diagnostic_report_category'],
    diagnostic_report_subject_id: ['diag_report_subject_id', 'subject_id', 'patient_id'],
    diagnostic_report_encounter_id: ['diag_report_encounter_id', 'encounter_id'],
    diagnostic_report_effective_date: ['diag_report_effective_date', 'effective_date'],
    diagnostic_report_effective_start: ['diag_report_effective_start', 'effective_start'],
    diagnostic_report_effective_end: ['diag_report_effective_end', 'effective_end'],
    diagnostic_report_issued: ['diag_report_issued', 'issued'],
    diagnostic_report_performer_id: ['diag_report_performer_id', 'performer_id'],
    diagnostic_report_result_ids: ['diag_report_result_ids', 'result_ids'],
    diagnostic_report_conclusion: ['diag_report_conclusion', 'conclusion'],
    diagnostic_report_note: ['diag_report_note', 'note']
  },
  relatedPerson: {
    related_person_id: ['related_person_id', 'relatedperson_id', 'rp_id'],
    related_person_active: ['related_person_active', 'active'],
    related_person_patient_id: ['related_person_patient_id', 'patient_id'],
    related_person_relationship: ['related_person_relationship', 'relationship'],
    related_person_first_name: ['related_person_first_name', 'first_name'],
    related_person_last_name: ['related_person_last_name', 'last_name'],
    related_person_phone: ['related_person_phone', 'phone'],
    related_person_email: ['related_person_email', 'email'],
    related_person_gender: ['related_person_gender', 'gender'],
    related_person_birth_date: ['related_person_birth_date', 'birth_date'],
    related_person_address_line1: ['related_person_address_line1', 'address_line1'],
    related_person_address_line2: ['related_person_address_line2', 'address_line2'],
    related_person_city: ['related_person_city', 'city'],
    related_person_state: ['related_person_state', 'state'],
    related_person_postal_code: ['related_person_postal_code', 'postal_code'],
    related_person_country: ['related_person_country', 'country']
  },
  location: {
    location_id: ['loc_id', 'location_identifier', 'locationid'],
    location_status: ['loc_status', 'status'],
    location_name: ['loc_name', 'name'],
    location_alias: ['loc_alias', 'alias'],
    location_description: ['loc_description', 'description'],
    location_mode: ['loc_mode', 'mode'],
    location_type: ['loc_type', 'type'],
    location_address_line1: ['loc_address_line1', 'address_line1'],
    location_address_line2: ['loc_address_line2', 'address_line2'],
    location_city: ['loc_city', 'city'],
    location_state: ['loc_state', 'state'],
    location_postal_code: ['loc_postal_code', 'postal_code'],
    location_country: ['loc_country', 'country'],
    location_managing_org_id: ['loc_managing_org_id', 'managing_organization_id'],
    location_part_of_id: ['loc_part_of_id', 'part_of_id']
  },
  specimen: {
    specimen_id: ['specimen_id', 'specimen_identifier', 'specimenid'],
    specimen_accession_identifier: ['accession_identifier', 'accession_id'],
    specimen_status: ['status'],
    specimen_type: ['type'],
    specimen_subject_id: ['subject_id', 'patient_id'],
    specimen_received_time: ['received_time'],
    specimen_parent_ids: ['parent_ids', 'parent_id'],
    specimen_request_ids: ['request_ids', 'request_id'],
    specimen_combined: ['combined'],
    specimen_role: ['role'],
    specimen_feature_type: ['feature_type'],
    specimen_feature_description: ['feature_description'],
    specimen_collection_collector_id: ['collection_collector_id', 'collector_id'],
    specimen_collection_collected_date: ['collection_collected_date', 'collected_date'],
    specimen_collection_collected_start: ['collection_collected_start', 'collected_start'],
    specimen_collection_collected_end: ['collection_collected_end', 'collected_end'],
    specimen_collection_duration_value: ['collection_duration_value', 'collection_duration'],
    specimen_collection_duration_unit: ['collection_duration_unit'],
    specimen_collection_quantity_value: ['collection_quantity_value', 'collection_quantity'],
    specimen_collection_quantity_unit: ['collection_quantity_unit'],
    specimen_collection_method: ['collection_method'],
    specimen_collection_device_id: ['collection_device_id', 'collection_device'],
    specimen_collection_procedure_id: ['collection_procedure_id', 'collection_procedure'],
    specimen_collection_body_site: ['collection_body_site'],
    specimen_collection_fasting_status: ['collection_fasting_status'],
    specimen_collection_fasting_duration_value: ['collection_fasting_duration_value', 'collection_fasting_duration'],
    specimen_collection_fasting_duration_unit: ['collection_fasting_duration_unit'],
    specimen_processing_description: ['processing_description'],
    specimen_processing_method: ['processing_method'],
    specimen_processing_additive_ids: ['processing_additive_ids', 'processing_additive_id'],
    specimen_processing_time_date: ['processing_time_date'],
    specimen_processing_time_start: ['processing_time_start'],
    specimen_processing_time_end: ['processing_time_end'],
    specimen_container_device_id: ['container_device_id', 'container_device'],
    specimen_container_location_id: ['container_location_id', 'container_location'],
    specimen_container_quantity_value: ['container_quantity_value', 'container_specimen_quantity_value'],
    specimen_container_quantity_unit: ['container_quantity_unit', 'container_specimen_quantity_unit'],
    specimen_condition: ['condition'],
    specimen_note: ['note']
  },
  imagingStudy: {
    imaging_study_id: ['imaging_study_id', 'imagingstudy_id', 'study_id'],
    imaging_study_identifier: ['imaging_study_identifier', 'study_identifier'],
    imaging_study_status: ['status'],
    imaging_study_modality: ['modality'],
    imaging_study_subject_id: ['subject_id', 'patient_id'],
    imaging_study_encounter_id: ['encounter_id'],
    imaging_study_started: ['started', 'study_started'],
    imaging_study_based_on_ids: ['based_on_ids', 'based_on_id'],
    imaging_study_part_of_ids: ['part_of_ids', 'part_of_id'],
    imaging_study_referrer_id: ['referrer_id', 'referrer'],
    imaging_study_endpoint_ids: ['endpoint_ids', 'endpoint_id'],
    imaging_study_number_of_series: ['number_of_series', 'series_count'],
    imaging_study_number_of_instances: ['number_of_instances', 'instance_count'],
    imaging_study_procedure: ['procedure'],
    imaging_study_location_id: ['location_id', 'location'],
    imaging_study_reason: ['reason'],
    imaging_study_note: ['note'],
    imaging_study_description: ['description'],
    imaging_series_uid: ['series_uid'],
    imaging_series_number: ['series_number'],
    imaging_series_modality: ['series_modality'],
    imaging_series_description: ['series_description'],
    imaging_series_number_of_instances: ['series_number_of_instances'],
    imaging_series_endpoint_ids: ['series_endpoint_ids', 'series_endpoint_id'],
    imaging_series_body_site: ['series_body_site'],
    imaging_series_laterality: ['series_laterality'],
    imaging_series_specimen_ids: ['series_specimen_ids', 'series_specimen_id'],
    imaging_series_started: ['series_started'],
    imaging_series_performer_id: ['series_performer_id', 'series_actor_id'],
    imaging_instance_uid: ['instance_uid'],
    imaging_instance_sop_class: ['instance_sop_class'],
    imaging_instance_number: ['instance_number'],
    imaging_instance_title: ['instance_title']
  },
  allergyIntolerance: {
    allergy_id: ['allergy_id', 'allergy_identifier', 'allergyintolerance_id'],
    allergy_clinical_status: ['clinical_status'],
    allergy_verification_status: ['verification_status'],
    allergy_type: ['type'],
    allergy_category: ['category'],
    allergy_criticality: ['criticality'],
    allergy_code: ['code', 'allergy_code'],
    allergy_code_system: ['code_system', 'allergy_code_system'],
    allergy_display: ['display', 'allergy_display'],
    allergy_patient_id: ['patient_id', 'subject_id'],
    allergy_encounter_id: ['encounter_id'],
    allergy_onset_date: ['onset_date', 'onset_datetime'],
    allergy_onset_start: ['onset_start'],
    allergy_onset_end: ['onset_end'],
    allergy_onset_text: ['onset_text'],
    allergy_recorded_date: ['recorded_date'],
    allergy_participant_actor_id: ['participant_actor_id'],
    allergy_participant_function: ['participant_function'],
    allergy_last_occurrence: ['last_occurrence'],
    allergy_note: ['note'],
    allergy_reaction_substance: ['reaction_substance'],
    allergy_reaction_manifestation: ['reaction_manifestation'],
    allergy_reaction_description: ['reaction_description'],
    allergy_reaction_onset: ['reaction_onset'],
    allergy_reaction_severity: ['reaction_severity'],
    allergy_reaction_exposure_route: ['reaction_exposure_route'],
    allergy_reaction_note: ['reaction_note']
  },
  immunization: {
    immunization_id: ['immunization_id', 'immunization_identifier', 'immunizationid'],
    immunization_status: ['status'],
    immunization_status_reason: ['status_reason'],
    immunization_vaccine_code: ['vaccine_code'],
    immunization_vaccine_system: ['vaccine_system'],
    immunization_vaccine_display: ['vaccine_display'],
    immunization_based_on_ids: ['based_on_ids', 'based_on_id'],
    immunization_administered_product_id: ['administered_product_id', 'administered_product'],
    immunization_manufacturer_id: ['manufacturer_id', 'manufacturer'],
    immunization_lot_number: ['lot_number'],
    immunization_expiration_date: ['expiration_date'],
    immunization_patient_id: ['patient_id', 'subject_id'],
    immunization_encounter_id: ['encounter_id'],
    immunization_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id'],
    immunization_occurrence_date: ['occurrence_date', 'occurrence_datetime'],
    immunization_occurrence_string: ['occurrence_string'],
    immunization_primary_source: ['primary_source'],
    immunization_information_source_id: ['information_source_id'],
    immunization_location_id: ['location_id', 'location'],
    immunization_site: ['site'],
    immunization_route: ['route'],
    immunization_dose_value: ['dose_value', 'dose'],
    immunization_dose_unit: ['dose_unit'],
    immunization_performer_actor_id: ['performer_actor_id', 'performer_id'],
    immunization_performer_function: ['performer_function'],
    immunization_note: ['note'],
    immunization_reason: ['reason'],
    immunization_is_subpotent: ['is_subpotent'],
    immunization_subpotent_reason: ['subpotent_reason'],
    immunization_program_eligibility_program: ['program_eligibility_program'],
    immunization_program_eligibility_status: ['program_eligibility_status'],
    immunization_funding_source: ['funding_source'],
    immunization_reaction_date: ['reaction_date'],
    immunization_reaction_manifestation: ['reaction_manifestation'],
    immunization_reaction_reported: ['reaction_reported'],
    immunization_protocol_series: ['protocol_series'],
    immunization_protocol_authority_id: ['protocol_authority_id'],
    immunization_protocol_target_disease: ['protocol_target_disease'],
    immunization_protocol_dose_number: ['protocol_dose_number'],
    immunization_protocol_series_doses: ['protocol_series_doses']
  },
  episodeOfCare: {
    episode_of_care_id: ['episode_id', 'episodeofcare_id', 'eoc_id'],
    episode_status: ['status'],
    episode_type: ['type'],
    episode_patient_id: ['patient_id', 'subject_id'],
    episode_managing_org_id: ['managing_organization_id', 'managing_org_id'],
    episode_period_start: ['period_start', 'start_date', 'start'],
    episode_period_end: ['period_end', 'end_date', 'end'],
    episode_care_manager_id: ['care_manager_id', 'care_manager'],
    episode_care_team_ids: ['care_team_ids', 'care_team_id', 'care_team'],
    episode_account_ids: ['account_ids', 'account_id', 'account'],
    episode_referral_request_ids: ['referral_request_ids', 'referral_request_id', 'referral_request'],
    episode_reason: ['reason'],
    episode_diagnosis: ['diagnosis'],
    episode_status_history_status: ['status_history_status'],
    episode_status_history_start: ['status_history_start'],
    episode_status_history_end: ['status_history_end']
  },
  carePlan: {
    care_plan_id: ['careplan_id', 'care_plan_identifier', 'careplan_identifier'],
    care_plan_status: ['status'],
    care_plan_intent: ['intent'],
    care_plan_category: ['category'],
    care_plan_title: ['title'],
    care_plan_description: ['description'],
    care_plan_subject_id: ['patient_id', 'subject_id'],
    care_plan_encounter_id: ['encounter_id'],
    care_plan_period_start: ['period_start', 'start_date', 'start'],
    care_plan_period_end: ['period_end', 'end_date', 'end'],
    care_plan_created: ['created', 'created_date'],
    care_plan_custodian_id: ['custodian_id', 'custodian'],
    care_plan_contributor_ids: ['contributor_ids', 'contributors'],
    care_plan_care_team_ids: ['care_team_ids', 'care_team_id', 'care_team'],
    care_plan_addresses: ['addresses', 'addressed'],
    care_plan_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id', 'supporting_info'],
    care_plan_goal_ids: ['goal_ids', 'goal_id', 'goals'],
    care_plan_activity_reference: ['activity_reference', 'planned_activity_reference'],
    care_plan_activity_progress: ['activity_progress'],
    care_plan_activity_performed: ['activity_performed', 'performed_activity'],
    care_plan_note: ['note'],
    care_plan_instantiates_canonical: ['instantiates_canonical'],
    care_plan_instantiates_uri: ['instantiates_uri'],
    care_plan_based_on_ids: ['based_on_ids', 'based_on_id'],
    care_plan_replaces_ids: ['replaces_ids', 'replaces_id'],
    care_plan_part_of_ids: ['part_of_ids', 'part_of_id']
  },
  careTeam: {
    care_team_id: ['careteam_id', 'care_team_identifier', 'careteam_identifier'],
    care_team_status: ['status'],
    care_team_category: ['category'],
    care_team_name: ['name', 'team_name'],
    care_team_subject_id: ['patient_id', 'subject_id'],
    care_team_period_start: ['period_start', 'start_date', 'start'],
    care_team_period_end: ['period_end', 'end_date', 'end'],
    care_team_participant_role: ['participant_role', 'role'],
    care_team_participant_member_id: ['participant_member_id', 'member_id', 'participant_member'],
    care_team_participant_on_behalf_of_id: ['participant_on_behalf_of_id', 'on_behalf_of_id'],
    care_team_participant_coverage_start: ['participant_coverage_start'],
    care_team_participant_coverage_end: ['participant_coverage_end'],
    care_team_reason: ['reason'],
    care_team_managing_org_ids: ['managing_org_ids', 'managing_org_id'],
    care_team_phone: ['phone'],
    care_team_email: ['email'],
    care_team_note: ['note']
  },
  goal: {
    goal_id: ['goal_identifier', 'goalid'],
    goal_lifecycle_status: ['lifecycle_status', 'status'],
    goal_achievement_status: ['achievement_status'],
    goal_category: ['category'],
    goal_continuous: ['continuous'],
    goal_priority: ['priority'],
    goal_description: ['description', 'goal_description'],
    goal_subject_id: ['subject_id', 'patient_id'],
    goal_start_date: ['start_date'],
    goal_start_code: ['start_code', 'start_codeable_concept'],
    goal_target_measure: ['target_measure'],
    goal_target_detail: ['target_detail', 'detail'],
    goal_target_due_date: ['target_due_date', 'due_date'],
    goal_status_date: ['status_date'],
    goal_status_reason: ['status_reason'],
    goal_source_id: ['source_id'],
    goal_addresses: ['addresses', 'addressed'],
    goal_note: ['note'],
    goal_outcome: ['outcome']
  },
  serviceRequest: {
    service_request_id: ['servicerequest_id', 'service_request_identifier', 'service_requestid'],
    service_request_status: ['status'],
    service_request_intent: ['intent'],
    service_request_category: ['category'],
    service_request_priority: ['priority'],
    service_request_do_not_perform: ['do_not_perform'],
    service_request_code: ['code'],
    service_request_code_system: ['code_system'],
    service_request_code_display: ['code_display'],
    service_request_subject_id: ['subject_id', 'patient_id'],
    service_request_encounter_id: ['encounter_id'],
    service_request_occurrence_date: ['occurrence_date', 'occurrence_datetime'],
    service_request_occurrence_start: ['occurrence_start'],
    service_request_occurrence_end: ['occurrence_end'],
    service_request_as_needed: ['as_needed'],
    service_request_authored_on: ['authored_on'],
    service_request_requester_id: ['requester_id'],
    service_request_performer_type: ['performer_type'],
    service_request_performer_ids: ['performer_ids', 'performer_id'],
    service_request_location_ids: ['location_ids', 'location_id'],
    service_request_reason: ['reason'],
    service_request_supporting_info_ids: ['supporting_info_ids', 'supporting_info_id'],
    service_request_specimen_ids: ['specimen_ids', 'specimen_id'],
    service_request_body_site: ['body_site'],
    service_request_note: ['note'],
    service_request_patient_instruction: ['patient_instruction'],
    service_request_instantiates_canonical: ['instantiates_canonical'],
    service_request_instantiates_uri: ['instantiates_uri'],
    service_request_based_on_ids: ['based_on_ids', 'based_on_id'],
    service_request_replaces_ids: ['replaces_ids', 'replaces_id'],
    service_request_requisition: ['requisition']
  },
  task: {
    task_id: ['task_identifier', 'taskid', 'task_id'],
    task_status: ['status'],
    task_intent: ['intent'],
    task_priority: ['priority'],
    task_do_not_perform: ['do_not_perform'],
    task_code: ['code'],
    task_code_system: ['code_system'],
    task_code_display: ['code_display'],
    task_description: ['description'],
    task_focus_id: ['focus_id'],
    task_for_id: ['for_id', 'beneficiary_id'],
    task_encounter_id: ['encounter_id'],
    task_requested_start: ['requested_start'],
    task_requested_end: ['requested_end'],
    task_execution_start: ['execution_start'],
    task_execution_end: ['execution_end'],
    task_authored_on: ['authored_on'],
    task_last_modified: ['last_modified'],
    task_requester_id: ['requester_id'],
    task_requested_performer_ids: ['requested_performer_ids', 'requested_performer_id'],
    task_owner_id: ['owner_id'],
    task_performer_id: ['performer_id'],
    task_performer_function: ['performer_function'],
    task_location: ['location'],
    task_reason: ['reason'],
    task_insurance_ids: ['insurance_ids', 'insurance_id'],
    task_note: ['note'],
    task_relevant_history_ids: ['relevant_history_ids', 'relevant_history_id'],
    task_instantiates_canonical: ['instantiates_canonical'],
    task_instantiates_uri: ['instantiates_uri'],
    task_based_on_ids: ['based_on_ids', 'based_on_id'],
    task_part_of_ids: ['part_of_ids', 'part_of_id'],
    task_group_identifier: ['group_identifier'],
    task_status_reason: ['status_reason'],
    task_business_status: ['business_status']
  },
  documentReference: {
    document_id: ['doc_id', 'document_identifier', 'documentid'],
    document_title: ['doc_title'],
    document_description: ['doc_description'],
    document_format: ['doc_format'],
    document_url: ['doc_url'],
    document_data: ['doc_data'],
    document_content_type: ['doc_content_type', 'mime_type'],
    document_status: ['doc_status']
  },
  practitioner: {
    practitioner_id: ['provider_id', 'clinician_id', 'practitioner_identifier', 'practitionerid'],
    practitioner_first_name: ['practitioner_given', 'practitioner_given_name', 'provider_first_name', 'clinician_first_name'],
    practitioner_middle_name: ['practitioner_middlename', 'provider_middle_name', 'clinician_middle_name'],
    practitioner_last_name: ['practitioner_family', 'practitioner_family_name', 'provider_last_name', 'clinician_last_name'],
    practitioner_name: ['practitioner_full_name', 'provider_name', 'clinician_name'],
    practitioner_gender: ['practitioner_sex', 'provider_gender', 'clinician_gender'],
    practitioner_birth_date: ['practitioner_dob', 'provider_dob', 'clinician_dob'],
    practitioner_phone: ['practitioner_phone_number', 'provider_phone', 'clinician_phone', 'practitioner_mobile', 'practitioner_home_phone'],
    practitioner_email: ['practitioner_email_address', 'provider_email', 'clinician_email'],
    practitioner_address_line1: ['practitioner_address', 'practitioner_address1', 'provider_address1', 'practitioner_address_1'],
    practitioner_address_line2: ['practitioner_address2', 'provider_address2', 'practitioner_address_2'],
    practitioner_city: ['practitioner_city', 'provider_city'],
    practitioner_state: ['practitioner_state', 'provider_state', 'practitioner_province'],
    practitioner_postal_code: ['practitioner_zip', 'provider_zip', 'practitioner_postal'],
    practitioner_country: ['practitioner_country', 'provider_country'],
    practitioner_qualification_code: ['practitioner_qualification', 'provider_qualification_code'],
    practitioner_qualification_system: ['practitioner_qualification_system', 'provider_qualification_system'],
    practitioner_qualification_display: ['practitioner_qualification_display', 'provider_qualification_display'],
    practitioner_active: ['provider_active', 'clinician_active']
  },
  practitionerRole: {
    practitioner_role_id: ['role_id', 'practitionerrole_id', 'practitioner_role_identifier'],
    practitioner_role_practitioner_id: ['role_practitioner_id', 'role_provider_id'],
    practitioner_role_organization_id: ['role_organization_id'],
    practitioner_role_code: ['role_code', 'practitionerrole_code'],
    practitioner_role_code_system: ['role_code_system'],
    practitioner_role_code_display: ['role_code_display'],
    practitioner_role_specialty: ['role_specialty', 'specialty_code'],
    practitioner_role_specialty_system: ['specialty_system'],
    practitioner_role_specialty_display: ['specialty_display'],
    practitioner_role_period_start: ['role_period_start', 'role_start'],
    practitioner_role_period_end: ['role_period_end', 'role_end'],
    practitioner_role_active: ['role_active']
  },
  organization: {
    organization_id: ['org_id', 'organization_identifier', 'organizationid'],
    organization_name: ['org_name', 'facility_name'],
    organization_alias: ['org_alias', 'organization_aliases'],
    organization_type_code: ['org_type_code', 'organization_type'],
    organization_type_system: ['org_type_system'],
    organization_type_display: ['org_type_display'],
    organization_phone: ['org_phone', 'organization_phone_number'],
    organization_email: ['org_email', 'organization_email_address'],
    organization_address_line1: ['org_address', 'org_address1', 'organization_address1', 'organization_address_1'],
    organization_address_line2: ['org_address2', 'organization_address2', 'organization_address_2'],
    organization_city: ['org_city', 'organization_city'],
    organization_state: ['org_state', 'organization_state', 'organization_province'],
    organization_postal_code: ['org_zip', 'organization_zip', 'organization_postal'],
    organization_country: ['org_country', 'organization_country'],
    organization_part_of: ['org_parent_id', 'parent_organization_id', 'organization_parent_id'],
    organization_active: ['org_active']
  }
};

export const HEADER_ALIASES: HeaderAliasMap = Object.values(HEADER_ALIAS_SECTIONS)
  .reduce((acc, section) => ({ ...acc, ...section }), {} as HeaderAliasMap);
